### ISSUE TITLE
Error code 141

### ISSUE THREAD

**Issue by HadrienG** [nf-core/mag#11]
the pipeline fails with `error code 141` whenever a pipe (`|`) is in a bash process.

This fails:
```
samtools view "${bam}" | awk '{print length(\$10)}' | head -1000 > checkm/read_length.txt
```

But this does not:
```
samtools view "${bam}" > rl_tmp_1
awk '{print length(\$10)}' < rl_tmp_1 > rl_tmp_2
head -1000 rl_tmp_2 > checkm/read_length.txt
```

**Comment by ewels** [comment]
This is very strange. We have pipes in a bunch of other pipelines (pun intended) and they work fine.. eg. [here](https://github.com/nf-core/rnaseq/blob/1cd5ab733a35727b01370de2ae8462d65f57fbb9/main.nf#L643) and lots of others.

**Comment by ewels** [comment]
I guess it's something to do with the `head` process exiting early. See https://stackoverflow.com/a/19120674/713980
