### ISSUE TITLE
kraken2_db_preparation failed

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [nf-core/mag#159]
I have checked the following places for my error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/mag pipeline documentation](https://nf-co.re/nf-core/mag/usage)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/mag -profile docker --input '*_{1,2}.fastq' --outdir /archive/karakulahg/nfcore-mag/analysis --host_genome GRCh38 --kraken2_db "/archive/db/kraken2db/maindb/kraken2db.tar.gz" --busco_reference "/archive/db/busco/bacteroidia_odb10.2021-02-23.tar.gz" --skip_krona`
2. See error: 
```
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'kraken2_db_preparation (1)'

Caused by:
  Process `kraken2_db_preparation (1)` terminated with an error exit status (2)

Command executed:

  tar -xf "kraken2db.tar.gz"

Command exit status:
  2

Command output:
  (empty)

Command error:
  tar: library/bacteria/library.fna: Cannot write: Input/output error
  tar: Exiting with failure status due to previous errors

Work dir:
  /archive/karakulahg/nfcore-mag/fastq/2sample_local_kraken/work/95/58ac74a21c56f1a5dbf611428aec6c

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

```

I expected to use my kraken2db in my local hpc. I compressed kraken2db into a tar.gz file. Could you please help me?

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline: nextflow run nf-core/mag -profile docker --input '*_{1,2}.fastq' --outdir /archive/karakulahg/nfcore-mag/analysis --host_genome GRCh38 --kraken2_db "/archive/db/kraken2db/maindb/kraken2db.tar.gz" --busco_reference "/archive/db/busco/bacteroidia_odb10.2021-02-23.tar.gz" --skip_krona
- [x] The [nextflow.log](https://github.com/nf-core/mag/files/6099467/nextflow.log) file 

## System

- Hardware: HPC with 36cpu,384gb memory, 20tb disk space, 100gbit network, no run limit, 
- Executor: local in conda environment created just for nextflow
- OS: CentOS Linux
- Version 7.3

## Nextflow Installation

- Version: ```
20.10.0 build 5430
  Created: 01-11-2020 15:14 UTC (18:14 EEST)
  System: Linux 3.10.0-1062.4.1.el7.x86_64
  Runtime: Groovy 3.0.5 on OpenJDK 64-Bit Server VM 10.0.2+13
  Encoding: UTF-8 (UTF-8)

```

## Container engine

- Engine: Docker
- version: ```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.4.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 376.4GiB
 Name: node03
 ID: KKSX:7ZZ4:5A2Q:5FKB:A4NG:PR24:XD36:MAMY:RK3W:Q3WX:PRBE:TKCT
 Docker Root Dir: /docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
- Image tag: nfcore/mag:1.2.0

## Additional context

My local kraken2db folder structure:
![image](https://user-images.githubusercontent.com/55430656/110286969-d3fa2300-7ff6-11eb-9214-1204ec5a6f48.png)

**Comment by d4straub** [comment]
Hi there,

I interpret the error message in your terminal `tar: library/bacteria/library.fna: Cannot write: Input/output error` that there was a problem with writing. This could be temporary connection issues (try run again with `-resume`, after all you use `/archive/...`), write permission issues (would expect error with "permission", though), space problems (would expect "no space left on device"). I'd first try with adding `-resume`, I think.
I do not see right now that this is a bug or a kraken database formatting problem.

**Comment by skrakau** [comment]
I will close this as I understood that this was not a mag issue. Feel free to reopen, in case the problem persists.
