### ISSUE TITLE
Migrate all parameter docs to JSON schema

### ISSUE THREAD

**Issue by apeltzer** [nf-core/mag#163]
Hi! 

this is not necessarily an issue with the pipeline, but in order to streamline the documentation group next week for the hackathon, I'm opening issues in all repositories / pipeline repos that might need this update to switch from parameter docs to auto-generated documentation based on the JSON schema. 

This will then supersede any further parameter documentation, thus making things a bit easier :-) 

If this doesn't apply (anymore), please close the issue. Otherwise, I'm hoping to have some helping hands on this next week in the documentation team on Slack https://nfcore.slack.com/archives/C01QPMKBYNR

**Comment by skrakau** [comment]
Hi, this is already done, partly in `master` and the remaining parts in `dsl2` (https://github.com/nf-core/mag/pull/162).

**Comment by apeltzer** [comment]
Even better, less things to do next week 😆
