### ISSUE TITLE
Process metabat requires too much time

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#166]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/mag pipeline documentation](https://nf-co.re/nf-core/mag/usage)

## Description of the bug

I perform currently a rather large assembly:
- 15 soil samples, Illumina only, `--coassemble_group --binning_map_mode "group"`
- SPAdes assembly not possible for me, estimated 3TB RAM required
- MEGAHIT assembly successful after 375h with 128 cpus and ~700GB RAM --> assembly: 14726955618 bytes ~15GB as fa.gz, 46.5 Gbases large, ~74 million contigs
- process metabat runs ages (>300h, 100 cores), toubleshooting:
  - metabat2 command requires ~12h, ~1200 MAGs produced
  - split_fasta.py requires too much time (>300h), uses only 1 cpu
  - split_fasta.py input is *.unbinned.fa that has a size of 5269544057 bytes ~ 5GB
  - split_fasta.py takes the following arguments: min_length_unbinned_contigs 100000 (instead of default 1000000), max_unbinned_contigs default, min_contig_size default

## Steps to reproduce

Well, apart from investing a lot of runtime, I'd not do that on purpose.

## Expected behaviour

This step should not take unreasonable long and would be best to be parallelized. With smaller assemblies that I performed with this pipeline the runtime was always reasonable.
Removing that step entirely seems not a good solution since #27 is still valid!

**Comment by skrakau** [comment]
Solved in https://github.com/nf-core/mag/pull/175
