### ISSUE TITLE
Compress or remove CAT raw files from results folder

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#180]
## Is your feature request related to a problem? Please describe

The results folder can be huge and (almost) all ways to reduce it are welcomed.
With mag v1.2.0, I had a case where `results/Taxonomy/*/raw/*` made up a fifth of the results folder storage space, compressing it saved several GB. This is the output of `CAT` that is also summarized in `results/Taxonomy/<Assembler>/*.bin2classification.names.txt`.

## Describe the solution you'd like

Compressing the folder content, i.e. `results/Taxonomy/*/raw/*`, would be great.

## Describe alternatives you've considered

Alternatively the `results/Taxonomy/*/raw` folder might be not needed in the results folder at all. Only the log file might deserve keeping.

**Comment by skrakau** [comment]
Solved in https://github.com/nf-core/mag/pull/193
