### ISSUE TITLE
Not quite sure why I'm getting this Busco error

### ISSUE THREAD

**Issue by gailrosen** [nf-core/mag#186]
Hi,

I think it's progressing.. but not quite sure why I'm getting this Busco error with MEGAHIT.  I took most of the files in the pipeline_info directory. 

Thanks,
Gail
[pipeline_info.zip](https://github.com/nf-core/mag/files/6421410/pipeline_info.zip)

**Comment by d4straub** [comment]
Did you try to resume? It seems to me like a file system problem.

**Comment by gailrosen** [comment]
I am just leaving it running.. which I believe the pipeline attempts to retry when it doesn't work?  You think the filesystem is not letting files be written to a specific directory?

**Comment by d4straub** [comment]
The pipeline attempts to retry usually only when the processes run into resource issues, not when they error because of other reasons. No, I speculate that its a file system hiccup so that a file was temporarily unavailable or not copied correctly. This seems to be no bug of the pipeline.

**Comment by skrakau** [comment]
Hi, the message `FileNotFoundError: [Errno 2] No such file or directory: 'busco_downloads/file_versions.tsv'` indicates that there might be a network problem, which BUSCO in that version did not properly report. In the next `mag` release there will be an option to run BUSCO in `offline` mode, but so far it needs network to download the `file_versions.tsv` file (not big) to check and report if there are newer versions of the lineage datasets available.

**Comment by gailrosen** [comment]
This sounds a little more reasonable -- as I have no clue what would be wrong with our filesystem.  I am not even sure where that directory is supposed to be... can I download the file_versions.tsv and fool it into thinking it was downloaded?

**Comment by skrakau** [comment]
Probably not (or it would have to be at a very specific time point at a very specific location). Rerunning using `-resume` as @d4straub mentioned should help, in case it is not a systematic network problem on your side.

**Comment by gailrosen** [comment]
One thing my sysadmin just noticed is that this is downloading stuff to my home directory, where he places a 64GB limit.... even though I'm trying to run everything from the larger shared /ifs directory.  Do you know if that busco_downloads is trying to go in there... can I force the pipeline not to use my home directory and to store things in other directories that I specify?  Thanks!

**Comment by skrakau** [comment]
BUSCO downloads the file into a folder within the `work` directory, in this case this is in `/ifs/.../TNT_wgs/`. Or if you specified a `scratch` directory, there. But that's a `nextflow` setting, not a `BUSCO` or `mag` specific behaviour. Maybe nextflow downloads files into your home directory, but that shouldn't be a size problem.

**Comment by gailrosen** [comment]
It finally finished.. these are the end files.  Not sure why Krona (with Kraken2 and taxonomic assignment didn't run... is that not a default?  It says "Skip_krona        : No"?) didn't run?

thanks,
Gail
[pipeline_info_end.zip](https://github.com/nf-core/mag/files/6428719/pipeline_info_end.zip)

**Comment by skrakau** [comment]
You would need to specify the kraken2 database with `--kraken2_db ` (see also https://nf-co.re/mag/1.2.0/parameters or use `--help`).

**Comment by gailrosen** [comment]
Thanks.  Not sure how this is supposed to be used.  I pulled the k2_pluspf_20210127.tar.gz database.  It errored out and seems to be trying only to do "tar xf" and not "tar xfz" so I decompressed the file.  But I still get an error.  I even tried to untar everything so it could find the expected k2d files.  But i still get the following error when running "nextflow run nf-core/mag -profile singularity --input 'CSJP002A_{R1,R2}.fastq.gz' -c nextflow.config --max_memory '186.GB' --max_cpus 20 --kraken2_db ../kraken2_db_plus_protozoa_fungi/k2_pluspf_20210127.tar"

and

[gailr@node005 Assembly_Binning_old]$ ls -l ../kraken2_db_plus_protozoa_fungi/
total 125734856
-rw-r--r-- 1 gailr gailr     2633638 Jan 25 14:08 database100mers.kmer_distrib
-rw-r--r-- 1 gailr gailr     2368734 Jan 25 15:56 database150mers.kmer_distrib
-rw-r--r-- 1 gailr gailr     2172211 Jan 25 18:15 database200mers.kmer_distrib
-rw-r--r-- 1 gailr gailr     2015809 Jan 25 21:04 database250mers.kmer_distrib
-rw-r--r-- 1 gailr gailr     1856924 Jan 26 00:23 database300mers.kmer_distrib
-rw-r--r-- 1 gailr gailr     3008505 Jan 25 11:50 database50mers.kmer_distrib
-rw-r--r-- 1 gailr gailr     2831915 Jan 25 12:51 database75mers.kmer_distrib
-rw-r--r-- 1 gailr gailr 53493044692 Jan 25 10:49 hash.k2d
-rw-r--r-- 1 gailr gailr     2182856 Jan 25 10:56 inspect.txt
-rw-rw-r-- 1 gailr gailr 53518428160 Jan 27 07:17 k2_pluspf_20210127.tar
-rw-r--r-- 1 gailr gailr          64 Jan 25 10:49 opts.k2d
-rw-r--r-- 1 gailr gailr     3766899 Jan 25 06:37 seqid2taxid.map
-rw-r--r-- 1 gailr gailr     2529898 Jan 25 06:50 taxo.k2d



--------

Error executing process > 'kraken2_db_preparation (1)'

Caused by:
  Missing output file(s) `*/*.k2d` expected by process `kraken2_db_preparation (1)`

Command executed:

  tar -xf "k2_pluspf_20210127.tar"

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /ifs/groups/eces450650Grp/data/Assembly_Binning_old/work/ad/090d71c71ff568764e9e894c69eab2

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by d4straub** [comment]
Again, this is obvious on the help page: https://nf-co.re/mag/dev/parameters#kraken2_db shows that an "tgz" is expected. You use another file (`k2_pluspf_20210127.tar`) than the recommended one. It is not a "tgz" file (`.tar`). So you are not using the pipeline as it is meant to be. What do you expect?

**Comment by gailrosen** [comment]
I did have it in tar.gz format -- but it did not work.  Isn't it a little too specific if it works with a tgz postfix and not a tar.gz postfix?

**Comment by gailrosen** [comment]
I just realize that maybe I have to bind that kraken directory to the singularity container.. maybe that's it.  i'll update

**Comment by gailrosen** [comment]
Yeah... I compressed it with gzip and renamed it and it is not working.. and I can't quite seem to figure out how to bind a directory to singularity when also using nextflow (at least not in my spare time)..... can you point me to a reference?

-[nf-core/mag] Pipeline completed with errors-                                       Error executing process > 'kraken2_db_preparation (1)'

Caused by:
  Missing output file(s) `*/*.k2d` expected by process `kraken2_db_preparation (1)`

Command executed:

  tar -xf "k2_pluspf_20210127.tgz"

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /ifs/groups/eces450650Grp/data/Assembly_Binning_old/work/6b/7071e8549c12729f7938422479caf2

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by skrakau** [comment]
There is no need to bind such directories to singularity. 

The mag pipeline currently assumes that within the input `*.tgz` or `.tar.gz` (both should work) is a folder that contains the `*.k2d` file, i.e. it is looking for a file `*/*.k2d` after unpacking. This was the case for previous prebuild kraken2 databases. If something changed, this would cause an error.

If this is the case it would be great if you could open a new issue describing this, while providing a link to the respective database which does not work. 

However, as an instant solution, you could create this directory structure yourself and compress it accordingly.

**Comment by skrakau** [comment]
I created a new issue https://github.com/nf-core/mag/issues/187 for now, please answer there so the different topics are not further mixed.
