### ISSUE TITLE
 Error: Database was built with a different version of Diamond and is incompatible.

### ISSUE THREAD

**Issue by skrakau** [nf-core/mag#188]
[pipeline_report.txt](https://github.com/nf-core/mag/files/6444837/pipeline_report.txt)
[software_versions.csv](https://github.com/nf-core/mag/files/6444838/software_versions.csv)

I don't know why, but I still get this error.   [2021-05-07 14:21:46.114194] 47 bin(s) found!  

Command error:
  Error: Database was built with a different version of Diamond and is incompatib
le.
  [2021-05-07 14:34:47.300571] ERROR: DIAMOND finished abnormally.

Work dir:
  /ifs/groups/eces450650Grp/data/Assembly_Binning_old/work/81/95fee99d939f76a9ae3
1784c62007d

Tip: you can replicate the issue by changing to the process work dir and entering
 the command `bash .command.run`

The workflow was completed at 2021-05-07T14:47:11.875034-
04:00 (duration: 1h 4m 7
s)

The command used to launch the workflow was as follows:

  nextflow run nf-core/mag -resume -profile singularity --input 'CSJP002A_{R1,R2}
.fastq.gz' -c nextflow.config --max_memory 186.GB --max_cpus 20 --kraken2_db k2_p
luspf_20210127.tar.gz --cat_db CAT_prepare_20210107.tar.gz --outdir results_cat

_Originally posted by @gailrosen in https://github.com/nf-core/mag/issues/74#issuecomment-834908121_

**Comment by skrakau** [comment]
Hi @gailrosen,

since you are using the latest release v1.2.0 and not the dev branch, the changes described in https://github.com/nf-core/mag/issues/74 do not yet apply for you (see also https://github.com/nf-core/mag/issues/90). 

It seems the pre-build CAT database versions compatible with the `Diamond` version used in mag `v1.2.0` are not available anymore on the [CAT download site](https://tbb.bio.uu.nl/bastiaan/CAT_prepare/). That is not ideal for reproducibility, and we try to address this problem in future releases.

For now you could a) build it yourself with an compatible DIAMOND version (more complicated) or b) ask the CAT developers for a compatible database, e.g. "http://tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20200304.tar.gz" (they provide it on request, easiest) or c) wait for the next mag release.

**Comment by gailrosen** [comment]
I still get the error when I try to use a different verison of DIAMOND.  ./diamond --version
diamond version 2.0.6

And I put that diamond in the --path_to_diamond  .... but it still gives the incompatibility flag.  Shouldn't I be able to make it use the diamond that I put in that path?  Or it's the fact that CAT is using a different version of DIAMOND?

**Comment by gailrosen** [comment]
[2021-05-19 10:31:17.324179] DIAMOND found: diamond version 0.9.24.

Ugh.. so it is finding an older DIAMOND.. where is it getting this from and why cannot i not overwrite it with --path_to_diamond  ?

**Comment by skrakau** [comment]
One solution for such problems in the future is to create the CAT database yourself within the mag pipeline (`--cat_db_generate`), ensuring the same DIAMOND version for building the database and running the classification. See #196. Will be part of the next release.

**Comment by gailrosen** [comment]
Hi,

It's unclear to me how to run --cat_db_generate.  Do I put the path of the db I want to generate afterward?  Should I still specify --cat_db?

Can  you give me an example of how to run this and where it saves the CAT db?

thanks,
Gail

________________________________________

**Comment by skrakau** [comment]
No, `--cat_db_generate` and `--cat_db` are mutually exclusive. The parameter `--cat_db_generate` is a boolean parameter, thus it's sufficient to just specify this  `--cat_db_generate`, maybe in combination with `--save_cat_db `. See https://github.com/nf-core/mag/pull/196.

However, not is only in the `dev` branch yet, release is in preparation.

**Comment by gailrosen** [comment]
ok thanks.

________________________________________
