### ISSUE TITLE
[Question] Reducing size of docker image 

### ISSUE THREAD

**Issue by tamuanand** [nf-core/mag#206]
Hi @skrakau

I am relatively new to Nextflow and using NF with Docker. I had a question which I posted to nf-core/atacseq about guidelines best practices for reducing docker image size.  https://github.com/nf-core/atacseq/issues/153#issue-897706705

I was wondering if you could help and share some guidelines?

As a general rule, how big can the Docker image can be before it is considered too large?

If I do docker build with the `environment.yml`, the image size comes close to 2.4 GB

Thanks in advance

**Comment by skrakau** [comment]
Hi @tamuanand,

if I see it right, your question is not related to a specific pipeline, right? Maybe the Nextflow Gitter chat would be more suitable to discuss such questions. However, with the Nextflow DSL2 conversions each process uses its own BioContainer, so the individual images will not be that big anymore (according releases for nf-core pipelines will come soon or are already out).

**Comment by skrakau** [comment]
I will close this, since there is no mag specific task or question anymore open. Feel free to reach out via nf-core Slack.

**Comment by tamuanand** [comment]
Thanks @skrakau for pointing me to BioContainers

One question - I see that `mag` [uses mulled containers](https://github.com/nf-core/mag/blob/8e41b19c2f63bef53053bae5cf5e0dda4d07d1ba/modules/local/bowtie2_assembly_align.nf#L18) - bowtie with samtools

The question: How do I get to know if I have a mulled container available for bwa + samtools. 

Thanks in advance

**Comment by skrakau** [comment]
https://github.com/nf-core/modules#software-requirements might help, otherwise the BioContainers team might be able to help.
