### ISSUE TITLE
Protein assemblies are reported to be better than genome assemblies

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#23]
Hey there,

just another thought that might be interesting:  De-novo protein-level assembler [Plass](https://github.com/soedinglab/plass) (described [here](https://www.nature.com/articles/s41592-019-0437-4.pdf?origin=ppub)) assembles six-frame-translated sequencing  reads  into  protein  sequences and is 10 times more sensitive than MEGAHIT or metaSPAdes (that we use in that pipeline).

Maybe it would be of advantage to have that as well. However, that is not exactly "assembly, binning and annotation of metagenomes", what do you think?

**Comment by HadrienG** [comment]
I'm currently trying plass of some of my data, and with [emapper](https://github.com/eggnogdb/eggnog-mapper) for the annotation I intend to see how well I can reconstruct pathways.

If it works well that would indeed be a really nice addition to the pipeline.
Do you have any results from `plass` yourself?

**Comment by d4straub** [comment]
I don't have any experience with Plass, I just came across their paper and thought this might be a good idea ;) 
When you come to positive results Plass could be implemented into one of the following releases.

**Comment by HadrienG** [comment]
An update on this: I ran plass + cd-hit + eggnog-mapper and it worked great!

I'd definitely recommend for any metagenomic study that looks into function, it's a nice complement to binning, as IMO it's a more unbiased overview of metabolism, where you don't discard unbinned contigs (even the small ones).

Deciding if we wanna include it in the pipeline and rename it "an all-in-one metagenomics pipeline" this is another question :-)

**Comment by d4straub** [comment]
Thanks for the update!
You are right, "mag" implies assembly, Plass shouldn't be the focus. Maybe its worth a thought again  when all other stuff works flawlessly and someone has too much time.
I close it for now.
