### ISSUE TITLE
Cannot use --skip_busco as --gtdb is always set?

### ISSUE THREAD

**Issue by mshamash** [nf-core/mag#232]
Hi,

In my testing I'd like to skip BUSCO analysis of bins, thus also skipping downstream taxonomy with GTDB-Tk, however when using the `--skip_busco` parameter, the following check in the WorkflowMag.groovy file seems to always be triggered, as `--gtdb` is set by default. I've tried setting `--gtdb NULL` at runtime, without much success. Does nf-core/mag require bin taxonomy to be done at the end of the workflow? I couldn't find any option to skip bin taxonomy, and just end up with my completed bins for analysis elsewhere.

Thanks in advance!

Line of code I am referencing:

https://github.com/nf-core/mag/blob/d4f00bc2d178c1c8dc25b576c9e77e70511d5d21/lib/WorkflowMag.groovy#L106-L109

**Comment by lch14forever** [comment]
Save error here. Manage to get it work using
```nextflow
--skip_busco --gtdb false
```

**Comment by mshamash** [comment]
Ah that's a good workaround/fix, much better than mine of commenting out the `gtdb` default parameter in the workflow files! I guess it's just a matter of having that documented somewhere perhaps.

**Comment by d4straub** [comment]
Agreed, `--skip_busco --gtdb false` is the way to go for now.

`params.gtdb` could be set to `false` when `--skip_busco` is used. Another way would be to add another parameter `--skip_gtdb` to prevent taxonomic classification of bins. I like the first option better.

**Comment by d4straub** [comment]
I solved it in the dev branch.
