### ISSUE TITLE
Update gtdbtk conda channel

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#251]
gtdb-tk conda channel might be wrong.

Current PR to solve this https://github.com/nf-core/mag/pull/238 is based on master branch, proper PR should do it.

**Comment by ropolomx** [comment]
Hi @d4straub. Do you mean this is because the `gtdb_conda_fix` branch is based on master? Should I close that PR and start a new one with the new branch based on `dev`?

**Comment by d4straub** [comment]
> Hi @d4straub. Do you mean this is because the gtdb_conda_fix branch is based on master? 

I think so, yes.

> Should I close that PR and start a new one with the new branch based on dev?

Would be awesome, yes, thanks!

**Comment by d4straub** [comment]
I have solved that.
