### ISSUE TITLE
test run completed with errors: metabat2

### ISSUE THREAD

**Issue by ScaonE** [nf-core/mag#253]
Hi all,

I was suggested to re-post here an issue I submitted @Slack in #help.

The command `nextflow run nf-core/mag -r 2.1.0 -profile test,docker;` did run but seems to have crashed on a metabat2 step, see attachment.

Relevant lines from `metabat2_binning.nf`:
```nextflow
19: include { getColNo } from '../../modules/local/functions'
70:         .map { meta, depth_file -> if (getColNo(depth_file) > 2) [meta, depth_file] }
```

The .nextflow.log states:
```
Nov-18 14:19:40.481 [main] INFO  nextflow.Nextflow - -[nf-core/mag] Pipeline completed with errors-
Nov-18 14:19:40.486 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (16)
Nov-18 14:19:40.589 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed WorkflowStats[succeededCount=40; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runni
ngCount=0; retriesCount=0; abortedCount=16; succeedDuration=9m 25s; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=17; peakCpus=28; peakMemory=102 GB; ]
...
Nov-18 14:19:41.138 [main] DEBUG nextflow.trace.TimelineObserver - Flow completing -- rendering html timeline
Nov-18 14:19:42.224 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Nov-18 14:19:42.251 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

![next](https://user-images.githubusercontent.com/1412265/142428055-ffd92830-b49f-44f7-ba37-d0d2f52a27f1.PNG)

I hope this helps. Tell me if you need additionnal info.

**Comment by d4straub** [comment]
Hi there, that seems weird, it looks like the `getColNo` was not imported from `'../../modules/local/functions'` after all.
Could you please execute it a second time with `-resume`, i.e.
`nextflow run nf-core/mag -r 2.1.0 -profile test,docker -resume`
just to make sure that this wasn't a read/write issue?

**Comment by ScaonE** [comment]
I do have this file: /home/fr_scaerw/.nextflow/assets/nf-core/mag/modules/local/functions.nf
(it is the right one, given that metabat2_binning.nf only refers to "../../modules/local/functions"?)

functions.nf seems to contains the needed func:
  `grep -i -A 5 "getcolno" ~/.nextflow/assets/nf-core/mag/modules/local/functions.nf`
>def getColNo(filename) {
    lines  = file(filename).readLines()
    return lines[0].split('\t').size()
}

**Comment by kaehwan** [comment]
Hi, @d4straub I faced the same issue too. However, when when to --skin_binning, the pipeline could work perfectly.

**Comment by ScaonE** [comment]
> Hi there, that seems weird, it looks like the `getColNo` was not imported from `'../../modules/local/functions'` after all. Could you please execute it a second time with `-resume`, i.e. `nextflow run nf-core/mag -r 2.1.0 -profile test,docker -resume` just to make sure that this wasn't a read/write issue?

One question when using -resume, will it take into account scripts modifications done after the first run? (in case I want to try to modify something & see if it helps the metabat2_binning step to run)

**Comment by d4straub** [comment]
Hi there, alright, that seems a more widespread issue, I'll see if I can reproduce it. Unfortunately I am locked up in a meeting today.
If you want to modify pieline files you should rather clone the repo and than execute with e.g. `nextflow run [path-to-repo] ....` instead of `nextflow run nf-core/ampliseq`

**Comment by ScaonE** [comment]
> Hi there, alright, that seems a more widespread issue, I'll see if I can reproduce it. Unfortunately I am locked up in a meeting today. If you want to modify pieline files you should rather clone the repo and than execute with e.g. `nextflow run [path-to-repo] ....` instead of `nextflow run nf-core/ampliseq`

Ok, I did clone & modify :
`cloned_repo_name/subworkflows/local/metabat2_binning.nf`;

I did comment the include call to the file where the function getColNo was imported
> // include { getColNo } from '../../modules/local/functions'

They I just c/c the function below from `cloned_repo_name/modules/local/functions.nf` to `cloned_repo_name/subworkflows/local/metabat2_binning.nf`:
>def getColNo(filename) {
 >   lines  = file(filename).readLines()
  >  return lines[0].split('\t').size()
>}

Lauching the pipe using `nextflow run ~/cloned_repo_name-profile test,docker;` did results in:
> Pipeline completed successfully

See attachement
![attach](https://user-images.githubusercontent.com/1412265/142634976-36ddf400-a6e3-4735-b299-c8ff0acc9a82.PNG)

**Comment by d4straub** [comment]
I am glad that you made it work for you!

However, I cannot reproduce this. Neither on (1) our cluster with singularity, nor (2) locally on my laptop with singularity or docker. And it does work (3) with github action tests with singularity, docker and conda. Additionally, it finishes successfully (4) on AWS.

**Comment by kaehwan** [comment]
Hi @ScaonE thanks for your solution.

I tried the pipeline with nextflow 21.10.0, it would reproduce the error.
However, the nf-core/mag pipeline worked well when older version of nextflow (21.4.0) was used.

**Comment by d4straub** [comment]
Found the problem, the pipeline fails with nextflow version 2.10.x.
Here the reproducible example:

- fails:

`NXF_VER=21.10.1 nextflow run nf-core/mag -r 2.1.0 -profile test,singularity`
`NXF_VER=21.10.0 nextflow run nf-core/mag -r 2.1.0 -profile test,singularity`

- succeeds:

`NXF_VER=21.04.3 nextflow run nf-core/mag -r 2.1.0 -profile test,singularity`

So the 20.10.x nextflow versions either contain a bug or an intentional change breaks the pipeline.
The solution for now is to use nextflow version 21.04.3 by prepending `NXF_VER=21.04.3` to your command thats start the pipeline.

That is a serious bug, so please keep the issue open. We will solve this soon-ish. Thanks for reporting the problem!

**Comment by d4straub** [comment]
Ok, that works in the dev branch again. I'll do soon a bug fix release (hopefully this week).
