### ISSUE TITLE
Process `NFCORE_MAG:MAG:CENTRIFUGE_DB_PREPARATION` terminated with an error exit status (9)

### ISSUE THREAD

**Issue by marcellosalvi** [nf-core/mag#259]
I'm trying to use the pipeline with the test config using GCP pluging. However I got this error that I'm not able to face with: Execution failed: generic::failed_precondition: while running "nf-e881f34f8882d2320c538d7c9284a73d-main": unexpected exit status 1 was not ignored. Do you have any suggestions?

## Steps to reproduce

Steps to reproduce the behaviour:

1. /home/marcello_salvi_ngdx_eu/nextflow main.nf -w 'gs://ngdx-scratch-west1/tmp' --tracedir. -profile docker,test 
2. See error: 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- version:

**Comment by d4straub** [comment]
You provided no information to work with. I am unable to help like this. The more details you provide, the more likely it is for me or anyone else to help.

**Comment by d4straub** [comment]
Closed due to inactivity.
