### ISSUE TITLE
Adding Unicycler as assembly choice for low diversity communities

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#26]
Hi there,

I'd like to propose to add [Unicycler](https://github.com/rrwick/Unicycler), which is also used in nf-core/bacass, and is rather specialized on single genomes but is also used successfully with low diversity communities (personal communication Daniel Huson). Unicycler is able to use Illumina and Nanopore data and perform hybrid assemblies. Unicycler also utilizes Spades which is already part of this pipeline.

My reasoning to use mag with Unicycler over bacass is because bacass is not meant for genome mixtures and has e.g. no binning and will develop rather not into supporting this.

Would you be ok to have Unicycler added?
I would first open a PR with Unicycler added to the environment (to check that the container still works when merged), and add in a second PR Unicycler into the main.nf.

**Comment by apeltzer** [comment]
To save you two countless hours: Unicycler 0.4.4 is fine, 0.4.7, 0.4.8 in bioconda are broken with random segfaults. Nobody knows why exactly. 

Use it in a separate ocntainer if possible, as we do in bacass too.

**Comment by apeltzer** [comment]
x-ref: https://github.com/bioconda/bioconda-recipes/pull/15605 

https://github.com/rrwick/Unicycler/issues/140#issuecomment-496222163

**Comment by HadrienG** [comment]
I have no experience with Unicycler for metagenomics but sure, if it works well for low-diversity samples why not!

**Comment by d4straub** [comment]
I tried it out (enrichment culture, 2 dominating genomes, but many low-abundance) and it worked out horribly. I think that wasn't a good idea!
