### ISSUE TITLE
Remote resource not found - due to not specifying version (-r)

### ISSUE THREAD

**Issue by stitam** [nf-core/mag#266]
Many thanks for developing this pipeline! I am stuck at step 3 of the Quick Start guide (https://nf-co.re/mag?q=metagenome, "Download the pipeline and test it on a minimal dataset with a single command").

```
nextflow run nf-core/mag -profile test,singularity
N E X T F L O W  ~  version 21.10.5
Pulling nfcore/mag ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nfcore/mag/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nfcore/mag/contents/main.nf
```
I believe the issue is caused by a typo.

This url does not exist (nfcore):
https://api.github.com/repos/nfcore/mag/contents/nextflow.config

This url exists (nf-core):
https://api.github.com/repos/nf-core/mag/contents/nextflow.config

Since the issue seems to be with pulling the repo I don't think this is a problem with nf-core/mag, but I was unsure where to raise this.

**Comment by d4straub** [comment]
Hi there!

I tested `nextflow pull nf-core/mag -r 2.1.1` and `nextflow run nf-core/mag -r 2.1.1 -profile test,singularity` and did not have any problem.
Do you have internet access on the machine you attempt to run the pipeline? Some clusters/cluster nodes do not have internet access and need offline execution.
Here is a more comprehensive guide, generally true for all nf-core pipelines: https://nf-co.re/usage/introduction

Let me know how it goes!

**Comment by stitam** [comment]
Thanks @d4straub for your quick reply! I can confirm that I have internet access, I am currently trying to run the pipeline locally. The code in the guide still fails on my end, however, when I specify the version number explicitly like you suggested it works! Would it be worth adding the version number to the code in the guide as well? If not, feel free to close the issue, and many thanks for your help!

**Comment by d4straub** [comment]
I think it is worth further investigation/confirmation and changing the documentation accordingly. Therefore I keep that issue open. Its sort of low priority for now.
Thanks for reporting the issue!

**Comment by d4straub** [comment]
Hm, actually, I cannot confirm the problem. When running a pipeline that was never run before with `nextflow run nf-core/<pipeline> -profile test,singularity`, it does work.

However, if one time you do specify the version (`-r`), you then have to specify it from then on. This might also apply to a pipeline that was first pulled with `-r`. Maybe that was the case here.

In summary, no changes needed.
