### ISSUE TITLE
Bowtie2 parameters are not passed on

### ISSUE THREAD

**Issue by maxibor** [nf-core/mag#268]
After working on #247 , I realized the bowtie2 options are not passed on properly by `options.args`, see details [here](https://github.com/nf-core/mag/pull/247#issuecomment-1024057537)

I suspect this will be fixed when the bowtie2 module will be switched the nf-core DSL2 v2 syntax.

1. Command line: `nextflow run nf-core/mag -profile docker,test_ancient_dna`

## Expected behaviour

The bowtie command should be:

```bash
...
bowtie2 \
    -p "2" \
    -x $INDEX \
     \ # here should be --very-sensitive-local -N 1
    -1 "test_minigut.phix_removed.unmapped_1.fastq.gz" -2 "test_minigut.phix_removed.unmapped_2.fastq.gz" \
    2> "SPAdes-test_minigut-test_minigut.bowtie2.log" |
...
```

## Log files

Have you provided the following extra information/files:

- [x] The command used to run the pipeline

## Container engine

- version: 2.2.0dev

**Comment by d4straub** [comment]
Could you please check whether that issue was solved by https://github.com/nf-core/mag/pull/269?

**Comment by skrakau** [comment]
Seems alright now with the current dev branch. The `.command.sh` of a `BOWTIE2_ASSEMBLY_ALIGN` process contains
```
...
bowtie2 \
    -p "2" \
    -x $INDEX \
    --very-sensitive-local -N 1 \
    -1 "test_minigut_sample2.phix_removed.unmapped_1.fastq.gz" -2 "test_minigut_sample2.phix_removed.unmapped_2.fastq.gz" \
    2> "SPAdes-test_minigut_sample2-test_minigut_sample2.bowtie2.log" |
    samtools view -@ "2" -bS |         samtools sort -@ "2" -o "SPAdes-test_minigut_sample2-test_minigut_sample2.bam"
samtools index "SPAdes-test_minigut_sample2-test_minigut_sample2.bam"
...
```

I will close this issue.

**Comment by maxibor** [comment]
Oh sorry, I forgot to check back on it.
Thanks for looking at @skrakau :)
