### ISSUE TITLE
Add publication instead of preprint

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#270]
Add brand new publication (https://doi.org/10.1093/nargab/lqac007) instead of preprint (https://doi.org/10.1101/2021.08.29.458094).

**Comment by jfy133** [comment]
Should also add to  https://nf-co.re/publications :sunglasses:

**Comment by d4straub** [comment]
Paper was added to website: https://nf-co.re/publications#nf-coremag

**Comment by d4straub** [comment]
That's done.
