### ISSUE TITLE
How is blastp called in the pipeline ?

### ISSUE THREAD

**Issue by gleveq1** [nf-core/mag#271]
Hi,

I'm just wondering at what point blast is loaded into the mag pipeline.

The pipeline seems to crash at the prokka step when blastp is called.

I don't see any singularity image or a module anywhere that contains the blastp call.

Also “nf-core modules list remote” does not show any existing blastp modules.

Thanks for any advice.

GL

**Comment by jfy133** [comment]
Hi @gleveq1 

I'm not a mag developer but can still partially answer your question:

BLAST is a dependency of prokka - i.e. it uses it internally. You can see this by looking at the dependency list of the bioconda recipe, which all nf-core modules are derived from

https://bioconda.github.io/recipes/prokka/README.html

Therefore it will be in the container somehow, and it could still be invoked even if not directly by MAG in the module.

So probably you would have to check the prokka documentation to debug, however if you post the actual error someone here might be able to give more pointers 👍

Cheers
James
