### ISSUE TITLE
Provide example successful output of "nf-core/mag -profile test,singularity"

### ISSUE THREAD

**Issue by prehensilecode** [nf-core/mag#278]
## Is your feature request related to a problem? Please describe
Running the self-test for singularity
```
nextflow run nf-core/mag -profile test,singularity
```
frequently fails, and at different points.

## Describe the solution you'd like
Full output of a completed successful test so that I have something to compare with.

(I am a sysadmin, and do not know anything about the components of this workflow.)

## Describe alternatives you've considered
Just blindly keep re-running the test. 

## Additional context
- Red Hat Enterprise Linux 8.1
- NextFlow 21.04.0
- Singularity 3.8.6 (via EPEL)
- Hardware
-- 2x Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz (hyperthreading enabled → 96 cores)
-- Memory: 376 GiB
-- Storage: local SSD 110 GiB

**Comment by d4straub** [comment]
Hi!
I typically try to assist with problem solving when there are issues with the pipeline. Pipeline output is described in detail in https://nf-co.re/mag/output and example output can be found at https://nf-co.re/mag/results. However, both of those resources do not specify exactly the test run output, so its not what you are asking for, I assume. https://nf-co.re/mag/results displays results of `-profile test_full`, that accesses data on AWS, typically (but not always) more reliable source than github files. You can find the test specifications in https://github.com/nf-core/mag/blob/master/conf/. Profile `test_full` has meaningful results and "real" datasets, in contrast to profile `test`, which has very small, meaningless data that is solely used for simple & fast testing or pipeline development.
So, essentially, I would recommend to use `-profile test_full` for your purpose with https://nf-co.re/mag/results.
Does that solve your issue for output examples?

**Comment by prehensilecode** [comment]
@d4straub Thanks for responding. I have "-profile test_full,singularity" currently running for a few hours. I think possibly part of the reason my prior runs failed was that I was running on a local partition with only about 100 GiB of free space. After moving to a BeeGFS filesystem with 170 TiB available, the run has continued for a few hours. Currently, the `work` directory is consuming 719 GiB, while the Singularity cache directory takes up 2.4 GiB.

I'll do a comparison of outputs once the test run has completed.

May I suggest adding a note about the requirements (disk space, etc.) needed to run the test suite in the "Quick Start" section of `README.md`.

**Comment by d4straub** [comment]
Well, `-profile test` runs even on my laptop in like 20 min, requires a few GB disk space, no need to over-complicate here. I agree though that it might be helpful to document somewhere requirements for `-profile test_full`. Is there a specific place you would have found/expected it?

**Comment by prehensilecode** [comment]
Current `-profile test_full,singularity` run failed on `NFCORE_MAG:MAG:PROKKA (MEGAHIT-CAPES_S7.14)`.  Output is too long to paste: please [see the gist](https://gist.github.com/prehensilecode/793a7acbb97fbcf399bce4734cfc9aad).

At the end of the run of test_full, `work` directory consumes 787 GiB, with 14 tests yet incomplete or failed. Singularity cache takes up 4.1 GiB.

Meanwhile, I'll try another run of `-profile test,singularity`.

**Comment by d4straub** [comment]
14 tests? Than your number for disk usage is pretty useless, isn't it?
There seems to be a problem that is unrelated to the pipeline code. The pipeline actually progresses quite far, but doesn't finish. Did you ever try the nextflow command `-resume`? Or in this case append `--skip_prokka -resume`? Also, the command line log is helpful, but the `.nextflow.log` file is more valuable (not that I am saying it would be of particular help here).

> Running the self-test for singularity
nextflow run nf-core/mag -profile test,singularity
frequently fails, and at different points.

Also indicates a non-pipeline related problem. `test` (and related profiles) work when your system works, is compatible with nextflow and uses compatible settings.

**Comment by prehensilecode** [comment]
OK. I'll check that Nextflow does work properly before trying nf-core/mag again. Thanks for taking time to explain.
