### ISSUE TITLE
error while I used gtdb database locally

### ISSUE THREAD

**Issue by DooYal** [nf-core/mag#279]
## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line:`sudo ~/miniconda3/envs/qimenv/bin/nextflow run nf-core/mag -r 2.1.1 -profile docker --input './samplesheet.csv' --host_fasta '/data/db/refgenome/human/GCF_000001405.39_GRCh38.p13_genomic.fna' --kraken2_db /data/db/nf-kk2/k2_pluspfp_16gb_20210517.tar.gz --gtdb /data/db/gtdb/gtdbtk_r202_data.tar.gz --skip_krona -resume --outdir './results_test`
2. See error: 
`Error executing process > 'NFCORE_MAG:MAG:GTDBTK:GTDBTK_DB_PREPARATION (gtdbtk_r202_data.tar.gz)'

Caused by:
  Process `NFCORE_MAG:MAG:GTDBTK:GTDBTK_DB_PREPARATION (gtdbtk_r202_data.tar.gz)` terminated with an error exit status (2)

Command executed:

  mkdir database
  tar -xzf gtdbtk_r202_data.tar.gz -C database --strip 1

Command exit status:
  2

Command output:
  (empty)

Command error:
  
  gzip: stdin: invalid compressed data--format violated
  tar: Unexpected EOF in archive
  tar: Unexpected EOF in archive
  tar: Error is not recoverable: exiting now
`

## System
- OS: Centos
- Version: CentOS Stream release 8

## Nextflow Installation
- Version: 21.10.6

## Container engine
- Engine: Docker

**Comment by d4straub** [comment]
Hi there,
that is a nasty error that seems to be related to an incomplete downloaded database.
`tar: Unexpected EOF in archive` hints to a incomplete file. Could you please make sure whether the database file you are referring to (gtdbtk_r202_data.tar.gz) is complete, i.e. size than its source? I would guess it does not. Re-downloading the database should fix the issue. Let me know whether this helps.

**Comment by DooYal** [comment]
> Hi there, that is a nasty error that seems to be related to an incomplete downloaded database. `tar: Unexpected EOF in archive` hints to a incomplete file. Could you please make sure whether the database file you are referring to (gtdbtk_r202_data.tar.gz) is complete, i.e. size than its source? I would guess it does not. Re-downloading the database should fix the issue. Let me know whether this helps.

Acutually it worked when I only typed `tar -xzf gtdbtk_r202_data.tar.gz -C database --strip 1`  for only uncompressed the database, but it can not work when I used nextflow.

**Comment by d4straub** [comment]
Hm, than I was wrong. Are you running this on a server? If yes, if it uses scratch or similar, it might be that the space isn't sufficient (but I would hope for a `No space left on device` error in that case). Could you use `-resume` to resume the pipeline and only re-run failed processes (i.e. `GTDBTK_DB_PREPARATION`)? To make sure its not some sort of temporal hick-up.

**Comment by DooYal** [comment]
> Hm, than I was wrong. Are you running this on a server? If yes, if it uses scratch or similar, it might be that the space isn't sufficient (but I would hope for a `No space left on device` error in that case). Could you use `-resume` to resume the pipeline and only re-run failed processes (i.e. `GTDBTK_DB_PREPARATION`)? To make sure its not some sort of temporal hick-up.

Yes, I run this on a server and 92% of space is available, however, it also did not work even I used `-resume`. In addition, the network connection is not so stable in my server, is this one of the causes?

**Comment by d4straub** [comment]
nf-core/mag allows to run on a server without any network connection, when all databases are supplied. And you did download the gtdbtk database beforehand, so network connectivity should not be the issue for that particular case.

Server space isn't equal to scratch space. If you have some sort of cluster/hpc setup than this is still a possibility. If this is a scratch space limitation, you might run into the problem with several processes.

Important question: is any process of the pipeline succeeding? Is `GTDBTK_DB_PREPARATION` the only one failing? Because it could be a general problem that isnt tied to that process. Both answers have to be "yes", otherwise let me know.

There are a few more things you can do: enter the working directory of the process `GTDBTK_DB_PREPARATION` (in `work/`) and execute the process manually with `bash .command.sh`. If that does not succeed, enter the working directory of the process `GTDBTK_DB_PREPARATION` and execute `tar -xzf gtdbtk_r202_data.tar.gz -C database --strip 1`. After one of those succeeded, use your `nextflow run nf-core/mag [...] -resume` and it should use the cached results in the `work` directory.

Let me know what works/doesnt work.

**Comment by DooYal** [comment]
> nf-core/mag allows to run on a server without any network connection, when all databases are supplied. And you did download the gtdbtk database beforehand, so network connectivity should not be the issue for that particular case.
> 
> Server space isn't equal to scratch space. If you have some sort of cluster/hpc setup than this is still a possibility. If this is a scratch space limitation, you might run into the problem with several processes.
> 
> Important question: is any process of the pipeline succeeding? Is `GTDBTK_DB_PREPARATION` the only one failing? Because it could be a general problem that isnt tied to that process. Both answers have to be "yes", otherwise let me know.
> 
> There are a few more things you can do: enter the working directory of the process `GTDBTK_DB_PREPARATION` (in `work/`) and execute the process manually with `bash .command.sh`. If that does not succeed, enter the working directory of the process `GTDBTK_DB_PREPARATION` and execute `tar -xzf gtdbtk_r202_data.tar.gz -C database --strip 1`. After one of those succeeded, use your `nextflow run nf-core/mag [...] -resume` and it should use the cached results in the `work` directory.
> 
> Let me know what works/doesnt work.

The process of `GTDBTK_DB_PREPARATION` was successed before, however, the pipeline was failed at the later process `NFCORE_MAG:MAG:MEGAHIT` at that time, and the server was re-configured later because of some hardware failure, and then the the pipeline is more early failed at `GTDBTK_DB_PREPARATION` this time.

**Comment by d4straub** [comment]
Ok, so all my troubleshooting was useless because you did not give those details. That means your system is faulty, this has nothing to do with the pipeline. Go to your system admin to fix the problem. If you want to try it without fixing the underlying problem, use the nextflow parameter `-resume` and brute-force it.

**Comment by DooYal** [comment]
> Ok, so all my troubleshooting was useless because you did not give those details. That means your system is faulty, this has nothing to do with the pipeline. Go to your system admin to fix the problem. If you want to try it without fixing the underlying problem, use the nextflow parameter `-resume` and brute-force it.

I re-downloaded the database, and the process is successful this time, so maybe the hardware failure mainly casused the loss of the gtdbtk database.

**Comment by DooYal** [comment]
> Ok, so all my troubleshooting was useless because you did not give those details. That means your system is faulty, this has nothing to do with the pipeline. Go to your system admin to fix the problem. If you want to try it without fixing the underlying problem, use the nextflow parameter `-resume` and brute-force it.

Now the gtdbtk process is successful, however,  the megahit process is failed...
`executor >  local (36)
[c6/743d39] process > NFCORE_MAG:MAG:FASTQC_RAW (test_minigut)                                                   [100%] 2 of 2 ✔
[ea/f9d56e] process > NFCORE_MAG:MAG:FASTP (test_minigut)                                                        [100%] 2 of 2 ✔
[76/af142c] process > NFCORE_MAG:MAG:BOWTIE2_HOST_REMOVAL_BUILD (GCF_000001405.39_GRCh38.p13_genomic.fna)        [100%] 1 of 1 ✔
[62/8fb1b0] process > NFCORE_MAG:MAG:BOWTIE2_HOST_REMOVAL_ALIGN (test_minigut-host_removed)                      [100%] 2 of 2 ✔
[3e/41fb06] process > NFCORE_MAG:MAG:BOWTIE2_PHIX_REMOVAL_BUILD (GCA_002596845.1_ASM259684v1_genomic.fna.gz)     [100%] 1 of 1 ✔
[d2/5bb54b] process > NFCORE_MAG:MAG:BOWTIE2_PHIX_REMOVAL_ALIGN (test_minigut-phix_removed)                      [100%] 2 of 2 ✔
[70/7a8bb0] process > NFCORE_MAG:MAG:FASTQC_TRIMMED (test_minigut)                                               [100%] 2 of 2 ✔
[-        ] process > NFCORE_MAG:MAG:NANOPLOT_RAW                                                                -
[-        ] process > NFCORE_MAG:MAG:PORECHOP                                                                    -
[-        ] process > NFCORE_MAG:MAG:NANOLYSE                                                                    -
[-        ] process > NFCORE_MAG:MAG:FILTLONG                                                                    -
[-        ] process > NFCORE_MAG:MAG:NANOPLOT_FILTERED                                                           -
[-        ] process > NFCORE_MAG:MAG:CENTRIFUGE_DB_PREPARATION                                                   -
[-        ] process > NFCORE_MAG:MAG:CENTRIFUGE                                                                  -
[58/ffdeea] process > NFCORE_MAG:MAG:KRAKEN2_DB_PREPARATION                                                      [100%] 1 of 1 ✔
[6b/a004d9] process > NFCORE_MAG:MAG:KRAKEN2 (test_minigut-k2_pluspfp_16gb_20210517)                             [100%] 2 of 2 ✔
[31/e46925] process > NFCORE_MAG:MAG:MEGAHIT (test_minigut)                                                      [100%] 2 of 2 ✔
[-        ] process > NFCORE_MAG:MAG:SPADESHYBRID                                                                -
[98/cba053] process > NFCORE_MAG:MAG:QUAST (MEGAHIT-test_minigut)                                                [100%] 2 of 2 ✔
[64/82d706] process > NFCORE_MAG:MAG:PRODIGAL (test_minigut)                                                     [100%] 2 of 2 ✔
[f3/cc4501] process > NFCORE_MAG:MAG:METABAT2_BINNING:BOWTIE2_ASSEMBLY_BUILD (MEGAHIT-test_minigut)              [100%] 2 of 2 ✔
[eb/57c2cd] process > NFCORE_MAG:MAG:METABAT2_BINNING:BOWTIE2_ASSEMBLY_ALIGN (MEGAHIT-test_minigut-test_minigut) [100%] 4 of 4 ✔
[26/bfeacd] process > NFCORE_MAG:MAG:METABAT2_BINNING:METABAT2 (MEGAHIT-test_minigut_sample2)                    [100%] 2 of 2, failed: 1 ✘
[-        ] process > NFCORE_MAG:MAG:METABAT2_BINNING:MAG_DEPTHS (MEGAHIT-test_minigut)                          -
[-        ] process > NFCORE_MAG:MAG:METABAT2_BINNING:MAG_DEPTHS_PLOT                                            -
[-        ] process > NFCORE_MAG:MAG:METABAT2_BINNING:MAG_DEPTHS_SUMMARY                                         -
[-        ] process > NFCORE_MAG:MAG:BUSCO_QC:BUSCO (MEGAHIT-test_minigut.1.fa)                                  -
[-        ] process > NFCORE_MAG:MAG:BUSCO_QC:BUSCO_PLOT                                                         -
[-        ] process > NFCORE_MAG:MAG:BUSCO_QC:BUSCO_SUMMARY                                                      -
[-        ] process > NFCORE_MAG:MAG:QUAST_BINS (MEGAHIT-test_minigut)                                           -
[-        ] process > NFCORE_MAG:MAG:QUAST_BINS_SUMMARY                                                          -
[-        ] process > NFCORE_MAG:MAG:CAT                                                                         -
[fb/e36ba5] process > NFCORE_MAG:MAG:GTDBTK:GTDBTK_DB_PREPARATION (gtdbtk_r202_data.tar.gz)                      [100%] 1 of 1 ✔
[-        ] process > NFCORE_MAG:MAG:GTDBTK:GTDBTK_CLASSIFY                                                      -
[-        ] process > NFCORE_MAG:MAG:GTDBTK:GTDBTK_SUMMARY                                                       -
[-        ] process > NFCORE_MAG:MAG:BIN_SUMMARY                                                                 -
[-        ] process > NFCORE_MAG:MAG:PROKKA (MEGAHIT-test_minigut.2)                                             -
[-        ] process > NFCORE_MAG:MAG:GET_SOFTWARE_VERSIONS                                                       -
[-        ] process > NFCORE_MAG:MAG:MULTIQC                                                                     -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'NFCORE_MAG:MAG:METABAT2_BINNING:METABAT2 (MEGAHIT-test_minigut_sample2)'

Caused by:
  Missing output file(s) `MetaBAT2/*.fa` expected by process `NFCORE_MAG:MAG:METABAT2_BINNING:METABAT2 (MEGAHIT-test_minigut_sample2)`

Command executed:

  OMP_NUM_THREADS=8 jgi_summarize_bam_contig_depths --outputDepth depth.txt MEGAHIT-test_minigut_sample2-test_minigut_sample2.bam MEGAHIT-test_minigut_sample2-test_minigut.bam
  metabat2 -t "8" -i "test_minigut_sample2.contigs.fa" -a depth.txt -o "MetaBAT2/MEGAHIT-test_minigut_sample2" -m 1500 --unbinned --seed 1
  
  gzip depth.txt
  mv depth.txt.gz "MEGAHIT-test_minigut_sample2-depth.txt.gz"
  
  # save unbinned contigs above thresholds into individual files, dump others in one file
  split_fasta.py "MetaBAT2/MEGAHIT-test_minigut_sample2.unbinned.fa" 1000000 100 1500
  
  # delete splitted file so that it doesnt end up in following processes
  rm "MetaBAT2/MEGAHIT-test_minigut_sample2.unbinned.fa"
  
  mkdir MetaBAT2/discarded
  gzip "MetaBAT2/MEGAHIT-test_minigut_sample2.lowDepth.fa"         "MetaBAT2/MEGAHIT-test_minigut_sample2.tooShort.fa"         "MetaBAT2/MEGAHIT-test_minigut_sample2.unbinned.pooled.fa"         "MetaBAT2/MEGAHIT-test_minigut_sample2.unbinned.remaining.fa"
  mv "MetaBAT2/MEGAHIT-test_minigut_sample2".*.fa.gz MetaBAT2/discarded/
  
  echo $(metabat2 --help 2>&1) | sed "s/^.*version 2\://; s/ (Bioconda.*//" > metabat2.version.txt

Command exit status:
  0

Command output:
  MetaBAT 2 (2.15 (Bioconda)) using minContig 1500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, maxEdges 200 and minClsSize 200000. with random seed=1
  0 bins (0 bases in total) formed.
  write MetaBAT2/MEGAHIT-test_minigut_sample2.unbinned.pooled.fa
  write MetaBAT2/MEGAHIT-test_minigut_sample2.unbinned.remaining.fa

Command error:
  Output depth matrix to depth.txt
  jgi_summarize_bam_contig_depths 2.15 (Bioconda) 2020-07-03T13:02:15
  Output matrix to depth.txt
  0: Opening bam: MEGAHIT-test_minigut_sample2-test_minigut_sample2.bam
  1: Opening bam: MEGAHIT-test_minigut_sample2-test_minigut.bam
  Processing bam files
  Thread 1 finished: MEGAHIT-test_minigut_sample2-test_minigut.bam with 99620 reads and 5 readsWellMapped
  Thread 0 finished: MEGAHIT-test_minigut_sample2-test_minigut_sample2.bam with 49978 reads and 9845 readsWellMapped
  Creating depth matrix file: depth.txt
  Closing most bam files
  Closing last bam file
  Finished

Work dir:
  /data/public/share/nf-core/data_mag/test-datasets-mag/test_data/work/26/bfeacd33c67a3ab2afe1d7f14799af

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line


Join mismatch for the following entries: 
- key=MEGAHIT-test_minigut.2.fa values= 
- key=MEGAHIT-test_minigut.1.fa values=
`
I think I should find an configured .yml file for MAG to creat a new work environment, which can avoid lots of common errors.

**Comment by d4straub** [comment]
Hi there.
I'll write it once more: This is not the fault of the pipeline. And also not of the software environment that comes with the pipeline.
If you need help fixing this problem, you might find advice in the nf-core slack channel #help, here how to join https://nf-core-invite.herokuapp.com/ or else google it. 
If you do not want to fix your system, use repeatedly `nextflow run [...your commands...] -resume`, `-resume` will only start the pipeline where it failed/did not progress yet. I have written that before, but looking at your command output, you did not follow my advice.
The failures come from your system, faulty settings or similar.

You do not follow my advice, so I close that issue.
