### ISSUE TITLE
Using -resume often re-starts processes that should be cached

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#280]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/mag pipeline documentation](https://nf-co.re/mag/usage)

## Description of the bug

Using `-resume` often re-starts processes that should be cached.

## Steps to reproduce

Steps to reproduce the behaviour:

```
nextflow run nf-core/mag -r 2.1.1 -profile test,singularity
nextflow run nf-core/mag -r 2.1.1 -profile test,singularity -resume
```
In that case I experience that `METABAT2` is partially re-run.

## Expected behaviour

-resume should not re-run any cached processes

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

I believe that is independent of the system but rather depends on possibly unsorted METABAT2 input.

## Nextflow Installation

- Version: 21.10.6

## Container engine

- Engine: Singularity
- version: 2.1.1

**Comment by skrakau** [comment]
Solved in https://github.com/nf-core/mag/pull/290
