### ISSUE TITLE
Including functional profile step

### ISSUE THREAD

**Issue by jacodela** [nf-core/mag#294]
## Is your feature request related to a problem? Please describe

`mag` currently implements taxonomic profiling and metagenome assembly, it would be greatly improved if a functional profile step was implemented, so that the functional profile of a metagenome could be obtained in addition to/without doing the whole metagenome assembly. 

## Describe the solution you'd like

The addition of a functional profiling step, using software such as [HUMAnN3](https://huttenhower.sph.harvard.edu/humann/) or similar

## Additional context

The mag pipeline would greatly benefit from a functional profiling tool; shallow sequenced metagenomes could be processed using `mag` to obtain functional and taxonomic profiles without requiring metagenome assembly. See [Nayfach et al](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004573) and [Hillmann et al](https://journals.asm.org/doi/10.1128/mSystems.00069-18)

Thanks,

Jacobo.

**Comment by d4straub** [comment]
I absolutely agree! I did not find time however to add HUMAnN3 to nf-core/tools, my [attempt](https://github.com/nf-core/modules/pull/1089) failed because lack of time.
I do think that this should be implemented.
