### ISSUE TITLE
Add a DOI on first release

### ISSUE THREAD

**Issue by apeltzer** [nf-core/mag#3]

**Comment by d4straub** [comment]
I do think this would be great for 1.1.0 since it seemed to be not addressed in 1.0.0

**Comment by skrakau** [comment]
It is already linked to Zenodo, so it will be automatically created for the (hopefully coming soon) next release.

Maybe we can close this issue, unless you think it should be created manually for the first release.

**Comment by d4straub** [comment]
No, thats great news!
