### ISSUE TITLE
Bowtie2 sections broken in MultiQC

### ISSUE THREAD

**Issue by skrakau** [nf-core/mag#311]
## Description of the bug

When host read removal is turned on (with `host_fasta` or `--host_genome` ), the Bowtie2 section for the assembly mappings is missing in the `MultiQC` report. This is due to the `--ignore "*.bowtie2.log"` parameter used in [MULTIQC](https://github.com/nf-core/mag/blob/e065754c46eedc85d46cd8a71b32ad73b3b741cb/modules/local/multiqc.nf#L47) when host read removal is activated. 

## Steps to reproduce

`nextflow run nf-core/mag -profile test_host_rm,<docker/singularity>`

**Comment by d4straub** [comment]
The `--ignore "*.bowtie2.log"` is still in version 2.3.0: https://github.com/nf-core/mag/blob/c9468cb9154402c4a4cab78664ee50c24a91f6c3/modules/local/multiqc.nf#L36
`-profile test_full` does specify `host_fasta` and indeed I cannot find a Bowtie2 section for the assembly mappings.
