### ISSUE TITLE
Consider adding checkM to the pipeline

### ISSUE THREAD

**Issue by jfy133** [nf-core/mag#326]
### Description of feature

CheckM is been updated to allow 'custom' paths to internal databases. We could now try adding it to the pipeline (Again)

**Comment by maxibor** [comment]
Checkm2 is (kind of) out, and from a brief look at the code, it looks that they reproduced the same mistake with singularity.
But it's been caught early enough (https://github.com/chklovski/CheckM2/issues/15), so hopefully by the time they release, it should work fine with singularity 

So I would suggest waiting for the fix and the release, and then integrate directly checkm2 instead.

**Comment by jfy133** [comment]
Done!
