### ISSUE TITLE
Busco Archive error

### ISSUE THREAD

**Issue by jfourquet2** [nf-core/mag#33]
Hi,
I wanted to test mag and I have this error when I run it with test profile or with our lab test samples:
`ERROR ~ No such file: https://busco-archive.ezlab.org/v3/datasets/bacteria_odb9.tar.gz`

I have tested `wget https://busco-archive.ezlab.org/v3/datasets/bacteria_odb9.tar.gz` and all works well.

Command lines:
nextflow run nf-core/mag -profile genotoul,test
nextflow run nf-core/mag --reads '*_R{1,2}.fastq.gz' -profile singularity,genotoul

Do you know this issue and how to solve it ?
Thanks a lot in advance !

**Comment by d4straub** [comment]
Download the file and use '--busco_reference bacteria_odb9.tar.gz'

**Comment by jfourquet2** [comment]
Thanks a lot, it works !
