### ISSUE TITLE
GTDB-TK fails due to insufficient memory

### ISSUE THREAD

**Issue by nayeimkhan** [nf-core/mag#336]
### Description of the bug

Hi, I have been trying to run the MAG pipeline with the latest version. However, the pipeline is failing at the GTDBTK_Classify step due to insufficient memory. Is there a workaround around the memory or is there a way to bypass the GTDB step? Any suggestions here will be helpful. Thanks!

### Command used and terminal output

```console
Command used - "nextflow run nf-core/mag -profile docker --input "$(pwd)/*_R{1,2}_001.fastq.gz" --outdir test_1 --skip_spades -r 2.2.1 --binning_map_mode own --skip_maxbin2 --skip_prokka --skip_prodigal --keep_phix true" 

Output
-[nf-core/mag] Pipeline completed with errors-
Error executing process > 'NFCORE_MAG:MAG:GTDBTK:GTDBTK_CLASSIFY '

Caused by:
  Process requirement exceed available memory -- req: 128 GB; avail: 123.2 GB
```

**Comment by skrakau** [comment]
Hi @nayeimkhan , you can use `--gtdb false` to skip the GTDB classification.

**Comment by nayeimkhan** [comment]
Thanks @skrakau for your suggestion!

**Comment by maxibor** [comment]
Newer versions of GTDB-Tk require significantly less memory than the one currently available in mag.
See https://github.com/Ecogenomics/GTDBTk#new-features
> This reduces the memory requirements of GTDB-Tk from 320 GB of RAM when using the full GTDB R07-RS207 reference tree to approximately 55 GB.

**Comment by d4straub** [comment]
I close this in favor of https://github.com/nf-core/mag/issues/409
