### ISSUE TITLE
nf-core/mag pipeline does not work

### ISSUE THREAD

**Issue by mglgc** [nf-core/mag#338]
### Description of the bug

The testing command 'nextflow run nf-core/mag -profile test,docker --outdir testdir' shows the next error:

N E X T F L O W  ~  version 22.04.3
Pulling nf-core/mag ...
WARN: Cannot read project manifest -- Cause: api.github.com
Cannot find `nf-core/mag` -- Make sure exists a GitHub repository at this address `https://github.com/nf-core/mag

Any feedback from the developers will be of valuable help. Thanks in advance.

**Comment by d4straub** [comment]
`Cause: api.github.com` seems to indicate to me that there is a problem with github availability. Could you try again?

**Comment by mglgc** [comment]
> 

Thank you for your reply.
I'm trying right now (in fact, since yesterday noon). Another pipeline as nf-core/rnaseq does work in the same computer.

**Comment by d4straub** [comment]
Another approach, please try:
```
nextflow pull nf-core/mag
nextflow pull nf-core/mag -r 2.2.1
nextflow run nf-core/mag -r 2.2.1 -profile test,docker --outdir testdir
```

**Comment by mglgc** [comment]
> Another approach, please try:
> 
> ```
> nextflow pull nf-core/mag
> nextflow pull nf-core/mag -r 2.2.1
> nextflow run nf-core/mag -r 2.2.1 -profile test,docker --outdir testdir
> ```

Any of those commands show the same error:

nextflow pull nf-core/mag
Checking nf-core/mag ...
WARN: Cannot read project manifest -- Cause: api.github.com
Cannot find `nf-core/mag` -- Make sure exists a GitHub repository at this address `https://github.com/nf-core/mag`

**Comment by d4straub** [comment]
I just tried those commands and all work for me flawlessly. Could you please try those command for another pipeline of your choice (now, i.e. time wise close to nf-core/mag)? I am a little lost why it shouldn't work for you right now for nf-core/mag if there isnt a general problem with your system.

**Comment by mglgc** [comment]
> I just tried those commands and all work for me flawlessly. Could you please try those command for another pipeline of your choice (now, i.e. time wise close to nf-core/mag)? I am a little lost why it shouldn't work for you right now for nf-core/mag if there isnt a general problem with your system.

nextflow pull nf-core/rnaseq shows the next error:
Checking nf-core/rnaseq ...
https://github.com/nf-core/rnaseq.git: cannot open git-upload-pac

**Comment by mglgc** [comment]
> > I just tried those commands and all work for me flawlessly. Could you please try those command for another pipeline of your choice (now, i.e. time wise close to nf-core/mag)? I am a little lost why it shouldn't work for you right now for nf-core/mag if there isnt a general problem with your system.
> 
> nextflow pull nf-core/rnaseq shows the next error: Checking nf-core/rnaseq ... https://github.com/nf-core/rnaseq.git: cannot open git-upload-pac

Any new firewall rule on my server, I guess?

**Comment by d4straub** [comment]
Yes, thats a problem on your end.

**Comment by mglgc** [comment]
> Yes, thats a problem on your end.

So please, may you point me to what firewall ports to open in order I can ask my server administrator for opening them? Thanks a lot.

**Comment by d4straub** [comment]
No, sorry, I can troubleshoot pipelines but I with this I cannot help you unfortunately.
Since this isnt a nf-core/mag pipeline, I'll close that here.
If you would like to have broader help also of (other!) people that can help with your current problem, feel free to [join nf-core](https://nf-co.re/join) slack, probably channel #help.
I'll close that issue but please feel free to open another one should you encounter other obstacles.

**Comment by mglgc** [comment]
> No, sorry, I can troubleshoot pipelines but I with this I cannot help you unfortunately. Since this isnt a nf-core/mag pipeline, I'll close that here. If you would like to have broader help also of (other!) people that can help with your current problem, feel free to [join nf-core](https://nf-co.re/join) slack, probably channel #help. I'll close that issue but please feel free to open another one should you encounter other obstacles.

Thanks again. I'll post at nf-core slack.
