### ISSUE TITLE
Starting the pipeline from assembled data

### ISSUE THREAD

**Issue by fbcorrea** [nf-core/mag#342]
### Description of feature

Hi, great work! Is there a way to start the pipeline with assembled data (contigs / scaffolds) and skip all the steps prior to that?

**Comment by d4straub** [comment]
Hi, no there is no such option currently. What is the application idea? That you only want to use the binning and downstream steps? For this raw data would be also of advantage because it is used in the binning step by providing sequencing depth information.

**Comment by fbcorrea** [comment]
Thank you, I think it makes sense to start from the beginning. The idea was that I have plenty of already assembled data, and that would save me some time. Also, people are starting to submit their assemblies to databases as well.
