### ISSUE TITLE
Mag with AWS Batch 

### ISSUE THREAD

**Issue by srajedwin** [nf-core/mag#354]
I try to run with mag on AWS Batch job queue with parameter values included for active job queue and AWS region

`nextflow run main.nf -profile awsbatch -bucket-dir s3://bucket1/temp --input samplesheet.csv --outdir s3://bucket1/results3 --awsqueue job-queue --awsregion ap-southeast-1`

The current nextflow version
 N E X T F L O W
      version 22.10.2 build 5832

I tried CLI and docker installed in a separate AMI and used this custom AMI to create AWS Batch compute environment as referred [here](https://www.nextflow.io/docs/edge/awscloud.html#configuration)

But pipeline exited with errors:

`Command executed:

 mkdir bowtie
  bowtie2-build --threads 1 GCA_002596845.1_ASM259684v1_genomic.fna.gz "bt2_index_base"
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BOWTIE2_PHIX_REMOVAL_BUILD":
      bowtie2: $(echo $(bowtie2 --version 2>&1) | sed 's/^.*bowtie2-align-s version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Command error:
  bash: /home/ec2-user/miniconda/bin/aws: /usr/bin/python2: bad interpreter: No such file or directory
  bash: /home/ec2-user/miniconda/bin/aws: /usr/bin/python2: bad interpreter: No such file or directory
` 

Look forward to your suggestions to fix this

Thanks.

**Comment by jfy133** [comment]
I've never run it mself, but I believe you  still need to specify the container system you wish to use (docker/singularity etc.) `awsbatch` just configures the executor?

**Comment by d4straub** [comment]
I close this doe to missing response.
