### ISSUE TITLE
Unbinned contigs not taxonomically assigned when `--refined-bins-only` set?

### ISSUE THREAD

**Issue by emnilsson** [nf-core/mag#357]
### Description of the bug

Hi there!
I’ve run mag with bin refinement with `DASTool` and taxonomic annotation with `CAT`  on the `--refined-bins-only`, and I’m now trying to find which file contains all the taxonomic annotations. If I understand the [docs](https://nf-co.re/mag/2.2.1/parameters#postbinning_input) properly, both bins and unbinned contigs should be passed to `CAT`, but I seem unable to find any `DASToolUnbinned` in the `CAT`-output (and no “not-Refined” either). 
Have I misunderstood that unbinned contigs are taxonomically assigned? Or am I looking in the wrong place?

### Command used and terminal output

```console
nextflow run nf-core/mag -r 2.2.0 -profile uppmax -params-file nextflow.yml -resume -c use_custom.config --refine_bins_dastool --skip_busco --postbinning_input 'refined_bins_only'
```

### Relevant files

[relevant_files.zip](https://github.com/nf-core/mag/files/10103532/relevant_files.zip)

### System information

Nextflow version: 22.10.1
Hardware: HPC
Executor: slurm
Container engine: Singularity/Apptainer
OS: Linux
mag version: 2.2.0

**Comment by jfy133** [comment]
Having to download the 180GB CAT file to debug before I can continue...

**Comment by jfy133** [comment]
OK wait, now I'm lookin at the right channels, after being prompted by the following (open) issue: https://github.com/nf-core/mag/issues/125

No - CAT is not run on unbinned contigs.

https://github.com/nf-core/mag/blob/a8e92af70eca59a92b72262e6cdde11e69375801/workflows/mag.nf#L563-L581

https://github.com/nf-core/mag/blob/a8e92af70eca59a92b72262e6cdde11e69375801/workflows/mag.nf#L629-L632

This would be an easy fix though as I can updat ethe channel that goes to `CAT` however I want to double check with @skrakau that there wasn't already a problem with unbinned going to CAT or not?

**Comment by jfy133** [comment]
Will close this for https://github.com/nf-core/mag/issues/125 but will also assign myself to that so can close that once we have the feedback from Sabrina :)
