### ISSUE TITLE
Allow to provide multiple FastQs per sample

### ISSUE THREAD

**Issue by alexhbnr** [nf-core/mag#358]
### Description of feature

In case, there is more than one pair of FastQ files per sample, e.g. because there are multiple libraries of a sample or the same library of a sample was sequenced multiple times, it would be great if these could be automatically be merged prior to starting the assembly during the pre-processing and host removal steps.

This could be solved by introducing an additional column with a library identifier in the sample sheet that is used for concatenating the different libraries of a sample.

**Comment by nick-youngblut** [comment]
It would be helpful to at least state in [docs](https://nf-co.re/mag/usage#input_specifications) that multiple fwd/rev reads for the same sample will not be merged at the start of the pipeline.

**Comment by jfy133** [comment]
Run merging support TODOs:

1. Update input samplesheet validation
2. Fix Kraken/SPADes issue
3. Post-map BAM merging
4. Update parameters

**Comment by jfy133** [comment]
Need to check if post-map BAM merging is necessary (only actually applies to mappign reads back to assemblies, but FASTQs shoudl already be merged).

Current question: how does  bbnorm integrate with the run merging... directly into? Should bbnorm'd reads go into other pipeline steps? (see slack)
