### ISSUE TITLE
I'm having a error with nf-core/mag

### ISSUE THREAD

**Issue by Irah-hari** [nf-core/mag#363]
### Description of the bug

Hi, Im running nf-core/mag 2.2.0 i am facing error with test data when i ran the command 

/home/hp/nextflow run nf-core/mag -r 2.2.0 -profile test,docker --outdir /home/hp/Documents/2.2.0

i have ran it using both version and facing the same error in Binning
it gives the following error. I greatly appreciate for all your help

### Relevant files

![Screenshot from 2022-12-05 18-13-40](https://user-images.githubusercontent.com/119855842/205642080-e6e2380b-684c-464b-93b3-4e2a3f0441d1.png)
![Screenshot from 2022-12-05 18-15-03](https://user-images.githubusercontent.com/119855842/205642089-8cd2a85e-ec5f-4bea-8e12-3ea43001d123.png)

### System information

Nextflow version :22.10.3
Hardware: Workstation
Container: Docker
Version of nf-core/mag : 2.2.0 & 2.2.1

**Comment by jfy133** [comment]
@Irah-hari good news, is this isn't a bug per-se. The pipeline still finishes successfully, just the test data we use is slightly suboptimal for MaxBin2! 

I will look into changing the colours to make it seem less bad!

**Comment by jfy133** [comment]
x-ref https://github.com/nf-core/tools/pull/2096
