### ISSUE TITLE
Help running in offline cluster

### ISSUE THREAD

**Issue by telatin** [nf-core/mag#37]
I need to run *mag* in offline mode and I tried with:
```bash
nextflow run $NF/nextflow/nf-core-mag-1.0.0/workflow/main.nf \
  --reads '$INPUT/reads/*_R{1,2}.fq.gz' \
  --busco_reference $DB/bacteria_odb9.tar.gz \
  --outdir out \
  --cat_db $DB/CAT_prepare_20190108.tar.gz \
  --kraken2_db $DB/minikraken2_v2_8GB_201904_UPDATE.tgz \
  --centrifuge_db $DB/p_compressed+h+v.tar.gz \
  -profile singularity
```

But I got an error from the KronaDB updater:
```
Caused by:
  Process `krona_db` terminated with an error exit status (1)

Command executed:
  ktUpdateTaxonomy.sh taxonomy

Command exit status:
  1

Command output:
  Creating taxonomy...
  
  Fetching taxdump.tar.gz...
  
  Update failed.
     Is your internet connection okay?

Command error:
  /opt/conda/envs/nf-core-mag-1.0.0/bin/ktUpdateTaxonomy.sh: line 163: [: ==: unary operator expected

Work dir:
  /qib/platforms/Informatics/GMH/nextflow/work/86/ca13b3e7b7dcc86ba54cb03e2f0d1b
```

I'd like to skip the `ktUpdateTaxonomy.sh` without skipping Krona plots, how can I do the step in advance (if required) and then run the workflow from the cluster? Thanks

**Comment by HadrienG** [comment]
At the moment you can't run krona in offline mode, that's an oversight on our part. I'll put this on the 1.1.0 release that should be out soon.

Thanks for bringing this up!

**Comment by telatin** [comment]
Ok thanks! I made a small change in the code to provide a taxonomy file in the meanwhile.

**Comment by d4straub** [comment]
@HadrienG any progress here?

**Comment by d4straub** [comment]
I do not run mag in offline mode, but that should work nowadays
