### ISSUE TITLE
save post-quality processed reads as FASTQ

### ISSUE THREAD

**Issue by plasmid02** [nf-core/mag#378]
### Description of feature

Add an option to save the quality filtered reads that are input for the assembly and taxonomic profiling sub-pipelines.  These would be very useful for use in other pipelines and applications.

**Comment by jfy133** [comment]
Good idea, and should be pretty easy to implement. I can do this once I'm back from holiday if no-one gets to it first!

**Comment by jfy133** [comment]
Done :) There are three flags depending at which level of preprocessing you wish to save the reads from
