### ISSUE TITLE
define the SPADES options and GTDB path

### ISSUE THREAD

**Issue by juejun14** [nf-core/mag#379]
### Description of the bug

hello,

I am learning to use your excellent pipeline, but I would like to ask two questions :
## First quetion 
**how to specify the SPADES options, such as "--metaviral" or "--rnaviral".**

I have tried "--spades_options --metaviral" or "--metaviral" directly.
It doesn't work.

Here is the command tested:
```bash
nextflow run nf-core/mag --input file_list_rna.csv --outdir output/D621 -profile singularity --max_memory 50.GB --max_cpus 30 --adapterremoval_adapter1 'GCCGGAGCTCTGCAGAATTC' --metaviral
N E X T F L O W  ~  version 22.04.5
Launching `https://github.com/nf-core/mag` [confident_church] DSL2 - revision: a8e92af70e [master]

WARN: Found unexpected parameters:
* --metaviral: true
- Ignore this warning: params.schema_ignore_params = "metaviral" 
``` 
-----------------------
## Second question
**Define the gtdb path not working**
I try to specify the gtdb path with "--gtdb 'gtdb/gtdbtk_r202_data.tar.gz' ", but it shows:
```bash
-[nf-core/mag] Pipeline completed with errors-
Error executing process > 'NFCORE_MAG:MAG:GTDBTK:GTDBTK_DB_PREPARATION (gtdbtk_r202_data.tar.gz)'

Caused by:
  Process `NFCORE_MAG:MAG:GTDBTK:GTDBTK_DB_PREPARATION (gtdbtk_r202_data.tar.gz)` terminated with an error exit status (2)

Command executed:

  mkdir database
  tar -xzf gtdbtk_r202_data.tar.gz -C database --strip 1
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:GTDBTK:GTDBTK_DB_PREPARATION":
      tar: $(tar --version 2>&1 | sed -n 1p | sed 's/tar (GNU tar) //')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  
  gzip: stdin: unexpected end of file
  tar: Unexpected EOF in archive
  tar: Unexpected EOF in archive
  tar: Error is not recoverable: exiting now

Work dir:
  /shared/ifbstor1/home/jchen/work/0e/c33247949bd6cbfe1930a7c1917ada

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

-------------
It looks like it doesn't use the path I define and re download the gtdb in work dir.

Thank you,

**Comment by d4straub** [comment]
> First quetion

`--spades_options "<spades-parameter>"`, i.e. is the spades-parameter is `--metaviral` (I didnt check) then use `--spades_options "--metaviral"`. The `"` are here pretty important, otherwise the pipeline assumes it is a pipeline parameter, but it is meant for spades, not the pipeline.

> Second question

That indicated a faulty file (`tar: Unexpected EOF in archive` -> `EOF` = end of file, i.e. a premature stop of the file, i.e. an incomplete file, for example when not downloaded completely). This isnt particularly unusual for large files such as this database. Re-download should help.

**Comment by juejun14** [comment]
> > First quetion
> 
> `--spades_options "<spades-parameter>"`, i.e. is the spades-parameter is `--metaviral` (I didnt check) then use `--spades_options "--metaviral"`. The `"` are here pretty important, otherwise the pipeline assumes it is a pipeline parameter, but it is meant for spades, not the pipeline.
> 
> > Second question
> 
> That indicated a faulty file (`tar: Unexpected EOF in archive` -> `EOF` = end of file, i.e. a premature stop of the file, i.e. an incomplete file, for example when not downloaded completely). This isnt particularly unusual for large files such as this database. Re-download should help.

Thank you for the reply!   

* Second question 
It works well after re download. I shouldn't be running multiple programs at the same time, I underestimated the space required to run this pipeline.

* First question
I have tried with ``` --spades_options "--metaviral" ``` but it didn't work.  

Error message:
```bash 
nextflow run nf-core/mag --input 'D589_S1_L001_R{1,2}*.fastq.gz' --outdir output_1301/ -profile singularity --max_memory 50.GB --max_cpus 30 --spades_options "--metaviral"
N E X T F L O W  ~  version 22.04.5
Launching `https://github.com/nf-core/mag` [clever_faggin] DSL2 - revision: a8e92af70e [master]

ERROR: Validation of pipeline parameters failed!

* --spades_options: expected type: String, found: Boolean (true)

WARN: Found unexpected parameters:
* --metaviral: true
- Ignore this warning: params.schema_ignore_params = "metaviral" 
```
I re read the  <a href="https://github.com/ablab/spades#sec3.2">document of SPADES<a/> and the spades.nf file of this pipeline. I realized that the option "--metaviral" is used with metaspadesviral.py, but the pipeline is working with metaspades.py (if i understand correctly). The option "--metaviral" will not work on this pipeline?

thanks,

**Comment by d4straub** [comment]
> First question
> I have tried with --spades_options "--metaviral" but it didn't work.

Alright, I tested myself, and made it work (well, at least no error on startup) with `--spades_options='--metaviral'`. Havent tried any further, just wanted to verify a pattern that works to get a param that way to `--spades_options`.

> I re read the [document of SPADES](https://github.com/ablab/spades#sec3.2) and the spades.nf file of this pipeline. I realized that the option "--metaviral" is used with metaspadesviral.py, but the pipeline is working with metaspades.py (if i understand correctly). The option "--metaviral" will not work on this pipeline?

It is possible that it wont work. Your reasoning seems good to me.

**Comment by d4straub** [comment]
I got another related question in nf-core/mag slack today:

> Is there a way to pass bowtie2 settings to nf-core/mag with the --bowtie2_mode parameter directly on the command line? I’m trying with quotes around the actual value: --bowtie2_mode "--very-sensitive" but then bowtie2_mode gets interpreted as an invalid parameter and very-sensitive ends up as an unexpected parameter. Is there a proper way to supply that bowtie2 string, or can it only be done via a config file?

It works with `--bowtie2_mode="--very-sensitive"`.
Essentially, I think that should go into the parameter description.

**Comment by juejun14** [comment]
> > First question
> > I have tried with --spades_options "--metaviral" but it didn't work.
> 
> Alright, I tested myself, and made it work (well, at least no error on startup) with `--spades_options='--metaviral'`. Havent tried any further, just wanted to verify a pattern that works to get a param that way to `--spades_options`. Edit: I think thats a documentation issue, its not clear imho. What do you think @skrakau ?
> 
> > I re read the [document of SPADES](https://github.com/ablab/spades#sec3.2) and the spades.nf file of this pipeline. I realized that the option "--metaviral" is used with metaspadesviral.py, but the pipeline is working with metaspades.py (if i understand correctly). The option "--metaviral" will not work on this pipeline?
> 
> It is possible that it wont work. Your reasoning seems good to me.

If anyone is interested : 
I have try to replace metaspades.py by spades.py in spades.nf, in this way it's possible to use spades option "--metaviral" or "--rnaviral"  with  ``` --spades_options='--metaviral' ``` 
And it can finish without problem

**Comment by d4straub** [comment]
Thanks for your feedback, yes, its indeed interesting that `--spades_options='--metaviral'` does work!

I close this in favor of https://github.com/nf-core/mag/issues/411
