### ISSUE TITLE
README.md -> URI typo

### ISSUE THREAD

**Issue by telatin** [nf-core/mag#38]
I found a minor problem in the README while setting up nf-core/mag for offline use:

in the **cat_db** section, this URI is not working for me (and if the * was intended, is causing a md format change):
```
Database for taxonomic classification of metagenome assembled genomes (default: none). E.g. "<tbb.bio.uu.nl/bastiaan/CAT*prepare/CAT_prepare_20190108.tar.gz>"
```
For me, this URI worked:
```
Database for taxonomic classification of metagenome assembled genomes (default: none). E.g. "<http://tbb.bio.uu.nl/bastiaan/CAT_prepare/CAT_prepare_20190108.tar.gz>"
```

**Comment by skrakau** [comment]
Thanks for reporting @telatin !
