### ISSUE TITLE
DASTool not generating bin files

### ISSUE THREAD

**Issue by rialc13** [nf-core/mag#386]
### Description of the bug

I ran multiple single end samples through the pipeline with --refine_bins_dastool true --postbinning_input refined_bins_only. The pipeline stops at the PROKKA step saying that the input file *.fa is not a readable non-empty FASTA file. A closer look at the *.fa file showed that the file is empty i.e. DAS Tool was unable to generate refined bin files. I understand that there might be cases where few samples may not generate refined bin files, however it would be better if the pipeline execution doesn't stop for the other samples generating refined bin files. 

### Command used and terminal output

```console
nextflow run /hdd_scratch4/mt539617/metagenomics/pipeline/mag-master-customized/main.nf --input '/hdd_scratch4/mt539617/metagenomics/output-with-dbref/RAW-PRJEB26427/*.fastq.gz' --host_fasta /hdd_scratch4/mt539617/metagenomics/pipeline/db_files/hg38.fa.gz --bowtie2_mode '--very-sensitive ' --host_removal_verysensitive true --binning_map_mode own --gtdb /hdd_scratch4/mt539617/metagenomics/pipeline/db_files/gtdbtk_r207_v2_data.tar.gz --centrifuge_db /hdd_scratch4/mt539617/metagenomics/pipeline/db_files/p_compressed+h+v.tar.gz --kraken2_db /hdd_scratch4/mt539617/metagenomics/pipeline/db_files/k2_standard_20220926.tar.gz --skip_krona false --busco_reference /hdd_scratch4/mt539617/metagenomics/pipeline/db_files/bacteria_odb10.2020-03-06.tar.gz --refine_bins_dastool true --postbinning_input refined_bins_only --outdir /hdd_scratch4/mt539617/metagenomics/output-with-dbref/OUT-PRJEB26427 -profile singularity --max_memory 70.GB --max_cpus 20 --single_end

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 2.

The full error message was:

Error executing process > 'NFCORE_MAG:MAG:PROKKA (*)'

Caused by:
  Process `NFCORE_MAG:MAG:PROKKA (*)` terminated with an error exit status (2)

Command executed:

  prokka \
      --metagenome \
      --cpus 2 \
      --prefix * \
       \
       \
      *.fa
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:PROKKA":
      prokka: $(echo $(prokka --version 2>&1) | sed 's/^.*prokka //')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  [23:57:10] This is prokka 1.14.6
  [23:57:10] Written by Torsten Seemann 
  [23:57:10] Homepage is https://github.com/tseemann/prokka
  [23:57:10] Local time is Thu Jan 26 23:57:10 2023
  [23:57:10] You are not telling me who you are!
  [23:57:10] Operating system is linux
  [23:57:10] You have BioPerl 1.007002
  [23:57:10] System has 96 cores.
  [23:57:10] Will use maximum of 2 cores.
  [23:57:10] Annotating as >>> Bacteria <<<
  [23:57:10] '*.fa' is not a readable non-empty FASTA file

Work dir:
  /hdd_scratch4/mt539617/metagenomics/output-with-dbref/work/f8/a4e141a58aaacb3ace8c2d02b6817c

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Relevant files

[PRJEB26427.zip](https://github.com/nf-core/mag/files/10543559/PRJEB26427.zip)

### System information

Nextflow version - version 22.10.6, build 5843 (23-01-2023 23:20 UTC)
Hardware - HPC
Container - Singularity
Version of nf-core/mag - nf-core/mag v2.2.1

**Comment by jfy133** [comment]
hi @rialc13 thanks for the report.

note I'm a bit wary here because you say you're using mag 2.2.1 but your command suggesting you're using a 'customised' version of mag `/hdd_scratch4/mt539617/metagenomics/pipeline/mag-master-customized/main.nf`

However I'll make the assumption that these are minor changes and don't affect the running of the pipeline at these steps.

Would it be possible for you to share the 'failed' FASTA file and also the `.command.log` file from the respective `DAS_Tool` process that genereted the failed FASTA file?

I need to see what exactly happend with DAS_Tool to generate a faulty FASTA, and see if I can work out a way to evaluate why it wasn't compatible with PROKKA to see if we can come up with a workaround to filter these out.

**Comment by rialc13** [comment]
Hi @jfy133 . 
I was able to solve this problem by updating the DAS tool container image to version 1.1.6 (currently the one used in the pipeline is version 1.1.4). This was a bug that the DAS tool developers solved in the latest version. Now, if the raw bins don't qualify the score threshold for DAS tool, then no file is generated (in the version 1.1.4, in case the raw bins didn't qualify the score threshold for DAS tool, an empty file named *.fa was being generated). Still for your reference, I'll share the 'failed' FASTA file and the DAS tool log file.  

[DASTool_error.zip](https://github.com/nf-core/mag/files/10553433/DASTool_error.zip)
PS. I transferred the *.fa file from my server to windows and the name changed to %2A.fa as windows doesn't allow you to use '*' character in file names.

**Comment by jfy133** [comment]
Thank you very much @rialc13 ! I wonder now if this is related to a bug I also reported a couple months ago! 

The latest version of DAS_Tool is already in the dev branch so hopefully this will be fixed in the next release :)

Please feel free to close the issue if you now have no more issues with the bumped das_tool version
