### ISSUE TITLE
Bin eukaryotic contigs separately using contig classifier

### ISSUE THREAD

**Issue by prototaxites** [nf-core/mag#388]
### Description of feature

A number of the tools for downstream analysis of MAGs within the pipeline are only appropriate for prokaryotic genomes, particularly Prokka, Prodigal, GTDB-Tk, and CheckM. Metagenomes that contain eukaryotic MAGs thus require some further downstream processing outwith the pipeline, for example for genome annotation.

One option would be to include a step following assembly to sort contigs into eukaryotic and prokaryotic contigs, using a tool such as EukRep or Tiara. These contig groups could then be binned separately, allowing lineage-specific tools to run only on bins for which they are appropriate, for example funannotate for eukaryotic genome annotation.

https://academic.oup.com/bioinformatics/article/38/2/344/6375939?login=false

**Comment by d4straub** [comment]
Sounds like a good idea to me!

**Comment by prototaxites** [comment]
I had a go at implementing this here: https://github.com/prototaxites/mag/tree/euk_split

Suffice to say, it doesn't work particularly well - overall, it puts out fewer bins of lower quality, and it doesn't work very well on the test data set, where it only identifies contigs as eukaryotic (which by my understanding, it shouldn't). In part, I think this is because the minimum contig size for reasonably accurate classification is quite large (3000bp). I'l leave the branch up though if anyone reading this wants to play with it.

The [VEBA pipeline](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-022-04973-8#Sec28) implements this differently, instead classifying all contigs within each bin, and generating a consensus domain classification. I might try my hand at this instead if I find time, as the majority of the bins I'm recovering from my data are eukaryotic (plant microbiomes are chock full of fungal endophytes!).

(n.b. I have also learned that DAS tool is also inappropriate for eukaryotic MAGs, as it relies on protein predictions using a prokaryote gene model - thus it might be best to put bin domain classification in the binning subworkflow so that only prokaryotic MAGs are fed into it)

**Comment by jfy133** [comment]
Good point about DAS_Tool + prokatyotes, can think how to deal with that in the future

**Comment by jfy133** [comment]
@prototaxites is this now addressed now Tiara is in there?

**Comment by prototaxites** [comment]
Think so!
