### ISSUE TITLE
Improvements - Possible merge with YAMP

### ISSUE THREAD

**Issue by HadrienG** [nf-core/mag#39]
This issue summarises the discussion that emerged at the London hackathon concerning a possible merge with [YAMP](https://github.com/alesssia/YAMP)

While MAG focuses heavily on assembly, YAMP is assembly-free and focuses on taxonomy classification and functional annotation of reads (and is quite human-centric at the moment)

What cam out of this discussion is that we'd like to combine both pipelines into one, since both approaches are very complementary.

A few things/kind of roadmap that came up in the discussion

- [ ] DSL2. MAG already has quite a lot of processes, and the code readability/maintainability would be better with modules/imports.
- [ ] We need to harmonise QC. YAMP currently uses bbduk while MAG uses fastp.
- [ ] There is a need for host removal. This steps exists in YAMP.
- [ ] Ideally the taxonomic classification will use kraken2/metaphlan. The choice would be left to the user.
- [ ] There should be a way to run only the YAMP (or the MAG) part. We already have flags to disable some parts of MAG so it should not be a problem.

cc @alesssia

**Comment by d4straub** [comment]
For assembly free taxonomic profiling there is nf-core/taxprofiler, for assembly based methods there is nf-core/mag. What is still missing is assembly free functional annotations such as HUMANN3 or the like.
YAMP merge seems to be currently out of picture.
