### ISSUE TITLE
Update used BioContainers to avoid memory reporting issue

### ISSUE THREAD

**Issue by skrakau** [nf-core/mag#401]
### Description of the bug

With BioContainers based on `busybox v1.22.1` the reported peak memory value in the `execution_trace` can be wrong (often 11 MB) due to a buggy `ps` output format for PIDs with 6 digits (see [slack message](https://nfcore.slack.com/archives/CE4K7FEHE/p1677059325987839)). With newer busybox versions this problem does not occur anymore v1.32.1, but the current SPADes and MEGAHIT containers, for example, still contain this old busybox version.

**Comment by jfy133** [comment]
This will be addressed anyway with future replacements of all local modules with official nf-core ones, so I will close this as that will definitely happen.
