### ISSUE TITLE
Update local GTDB-Tk module to newest nf-core module

### ISSUE THREAD

**Issue by skrakau** [nf-core/mag#409]
### Description of feature

The current used version, i.e. v 1.5.0, of GTDB-Tk requires large amounts of memory, which is improved by newer GTDB-Tk versions. See also https://github.com/nf-core/mag/issues/336

Currently still a local module is used, but it seems that the [nf-core `classifywf` module](https://github.com/nf-core/modules/tree/master/modules/nf-core/gtdbtk/classifywf) which was also recently updated to version 2.1.1 could be used.

**Comment by jfy133** [comment]
Wait,m I just noticed this module is broken - there is a mistmatch between conda and container vcersions :scream:

**Comment by alxndrdiaz** [comment]
> Wait,m I just noticed this module is broken - there is a mistmatch between conda and container vcersions scream

@jfy133 Not sure if this has been module updated, but here is the  the new PR https://github.com/nf-core/mag/pull/448: All container images updated to GTDBTk v2.1.1

**Comment by alxndrdiaz** [comment]
I confirm this was fixed by #438, so this PR will be closed.
