### ISSUE TITLE
Add digital normalization

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/mag#412]
### Description of feature

Digital normalization is used to reduce the sequencing depth of input data before assembly. This has two advantages. First, it makes assembly simpler and hence less resource hungry. Second, assemblies can presumably be better with less, but still representative, input data.

There are modules available for two approaches, [khmer](https://khmer.readthedocs.io/en/latest/) and [BBnorm](https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/bbnorm-guide/). We have better experiences with the latter.

**Comment by erikrikarddaniel** [comment]
I've added BBnorm to the pipeline in my fork. There's still some checking to do, and update of documentation.

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/mag/pull/422
