### ISSUE TITLE
Hardcoded url in main workflow

### ISSUE THREAD

**Issue by erikrikarddaniel** [nf-core/mag#414]
### Description of the bug

There's a hardcoded url in line 221 in `workflows/mag.nf`. It looks a bit funny to me, and I'd be happy to make a PR and move it to a parameter with a default (hidden?), but @d4straub thought there might be a reason for it being there, hence this bug report.

### Relevant files

workflows/mag.nf

**Comment by jfy133** [comment]
Ups, my bad - you're right - fixing!
