### ISSUE TITLE
Test data samplesheet is using old S3 paths

### ISSUE THREAD

**Issue by Lfulcrum** [nf-core/mag#415]
### Description of the bug

The samplesheet used by the `test_full` profile is still using old S3 paths for test input data. These should be corrected to the new S3 paths.

I've edited the samplesheet content (at https://ngi-igenomes.s3.amazonaws.com/test-data/mag/samplesheets/samplesheet.full.csv) to contain corrected new S3 paths that work at present:
```
sample,group,short_reads_1,short_reads_2,long_reads
CAPES_S11,0,s3://ngi-igenomes/test-data/mag/ERR3201918_1.fastq.gz,s3://ngi-igenomes/test-data/mag/ERR3201918_2.fastq.gz,s3://ngi-igenomes/test-data/mag/ERR3201942.fastq.gz
CAPES_S21,0,s3://ngi-igenomes/test-data/mag/ERR3201928_1.fastq.gz,s3://ngi-igenomes/test-data/mag/ERR3201928_2.fastq.gz,s3://ngi-igenomes/test-data/mag/ERR3201952.fastq.gz
CAPES_S7,0,s3://ngi-igenomes/test-data/mag/ERR3201914_1.fastq.gz,s3://ngi-igenomes/test-data/mag/ERR3201914_2.fastq.gz,s3://ngi-igenomes/test-data/mag/ERR3201938.fastq.gz
```

The paths for other input files specified in the master [test_full.config](https://github.com/nf-core/mag/blob/c9468cb9154402c4a4cab78664ee50c24a91f6c3/conf/test_full.config) are corrected in the dev branch [test_full.config](https://github.com/nf-core/mag/blob/a65fbd44660168c1bbfa7cc47c870678bbf64258/conf/test_full.config).

### Command used and terminal output

Running with the test_full profile:
```
nextflow run nf-core/mag -r dev -profile test_full,singularity --outdir test_full_output
```

Returns the following error:
```
No such file: s3://nf-core-awsmegatests/mag/input_data/ERR3201918_1.fastq.gz
```

**Comment by jfy133** [comment]
Thanks @Lfulcrum I'll try and fix that today

**Comment by jfy133** [comment]
Step one: https://github.com/nf-core/test-datasets/pull/870

**Comment by jfy133** [comment]
Step two :point_up:

**Comment by jfy133** [comment]
Done! Thanks again @Lfulcrum
