### ISSUE TITLE
Error executing CONCOCT: Process exceeded running time limit (4h)

### ISSUE THREAD

**Issue by mlbonatelli** [nf-core/mag#423]
### Description of the bug

Hi there,

I am running nf-core/mag on a conda environment, and when I ran the test (nextflow run nf-core/mag -r 2.3.0 -profile test,singularity --outdir /work/bonatell/nf-core/testDir), process finished successfully.

However, now that I am running with my own samples, I am getting this error message:

**Error executing process > 'NFCORE_MAG:MAG:BINNING:FASTA_BINNING_CONCOCT:CONCOCT_CONCOCT (CH10_R)'**
**Caused by:
  Process exceeded running time limit (4h)**

I hope I am providing enough information, but if not, please let me know what you need to help me fix this problem.

Thanks,
Maria

### Command used and terminal output

```console
#COMMAND
nextflow run nf-core/mag -r 2.3.0 --input '/path/to/CH10_R{1,2}_001.fastq.gz' --outdir /work/bonatell/nf-core/testCH10 -profile singularity

#ERROR MESSAGE
Error executing process > 'NFCORE_MAG:MAG:BINNING:FASTA_BINNING_CONCOCT:CONCOCT_CONCOCT (CH10_R)'**

Caused by:
  Process exceeded running time limit (4h)

Command executed:

  concoct \
       \
      --threads 2 \
      --coverage_file MEGAHIT-CONCOCT-CH10_R.tsv \
      --composition_file MEGAHIT-CONCOCT-CH10_R.fasta \
      -b MEGAHIT-CONCOCT-CH10_R

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BINNING:FASTA_BINNING_CONCOCT:CONCOCT_CONCOCT":
      concoct: $(echo $(concoct --version 2>&1) | sed 's/concoct //g' )
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Command error:
  Generate input data
  0,-18951583.355273,369046.398338
  1,-18752372.048079,199211.307194
  2,-18639427.073650,112944.974428
  3,-18564503.408093,74923.665557
  4,-18509096.684479,55406.723615
  5,-18465425.484156,43671.200323
  6,-18431163.690157,34261.793998
  7,-18404080.220047,27083.470110
  8,-18380534.216416,23546.003632
  9,-18359280.087466,21254.128949
  10,-18339016.560793,20263.526674
  11,-18318104.609939,20911.950853
  12,-18296610.062952,21494.546987
  13,-18278524.271292,18085.791660
  14,-18262587.583239,15936.688053
  15,-18247803.542311,14784.040928
  16,-18233837.545631,13965.996681
  17,-18220386.638179,13450.907452
  18,-18208126.663919,12259.974260
  19,-18196472.151367,11654.512552
  20,-18186360.396028,10111.755340
  21,-18177005.961354,9354.434674
  22,-18167336.572377,9669.388977
  23,-18156761.117584,10575.454793
  24,-18149433.808884,7327.308700
  25,-18142630.157047,6803.651837
  26,-18136119.057171,6511.099875
  27,-18129772.233428,6346.823743
  28,-18123418.732754,6353.500674
  29,-18117158.101586,6260.631168
  30,-18111100.454178,6057.647407
  31,-18105232.243026,5868.211152
  32,-18099247.922074,5984.320952
  33,-18092854.167240,6393.754834
  34,-18086691.712485,6162.454756
  35,-18080225.389765,6466.322719
  36,-18073188.127150,7037.262616
  37,-18065761.364827,7426.762323
  38,-18058373.282924,7388.081903
  39,-18051355.154159,7018.128764
  40,-18045561.704637,5793.449523
  41,-18040572.690959,4989.013678
  42,-18035870.439474,4702.251485
  43,-18030864.587929,5005.851544
  44,-18026072.889266,4791.698663
  45,-18021569.700004,4503.189262
  46,-18015603.491556,5966.208448
  47,-18010802.440893,4801.050663
  48,-18007421.904891,3380.536002

Work dir:
  /gpfs1/work/bonatell/work/e6/05bd41ccb6dd38d5433ed60193577e

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


Join mismatch for the following entries:
- key=[id:CH10_R, group:0, single_end:false, assembler:MEGAHIT, binner:CONCOCT] values=[/gpfs1/work/bonatell/work/48/3e519cf2d76e21f093b426e86de4fb/MEGAHIT-CH10_R.contigs.fa]
- key=[id:CH10_R, group:0, single_end:false, assembler:SPAdes, binner:CONCOCT] values=[/gpfs1/work/bonatell/work/c8/adc81233b49ffd3fc782d4df2da98d/SPAdes-CH10_R_scaffolds.fasta]
```

### System information

Nextflow version (22.10.6)
Hardware (HPC)
Executor (slurm)
Container engine: (Singularity)
OS (Linux)
Version of nf-core/mag (2.3.0)

**Comment by d4straub** [comment]
Hi there, thanks for the feedback!
Generally, times can vary extremely between samples and assemblies, that means its very hard to get the resource settings right. I think we should review the settings for that process.
In the meanwhile, you can fix the problem with appending to your nextflow command `-c CONCOCT.config -resume` where `CONCOCT.config` contains:
```
process {
    withName: CONCOCT_CONCOCT {
        cpus   = 2
        memory = 12.GB
        time   = 12.h
    }
}
```
cpus and memory is here set on default, but I would recommend you increase them as well a little to be sure.

**Comment by mlbonatelli** [comment]
Oh, that's great! Thanks, I will do that!

**Comment by mlbonatelli** [comment]
Hi! 

Unfortunately, it did not work with the new configuration for CONCOCT, as you can see bellow:

**Error executing process > 'NFCORE_MAG:MAG:BINNING:FASTA_BINNING_CONCOCT:CONCOCT_CONCOCT (CH10_R)'**

Caused by:
  Process exceeded running time limit (12h)

Command executed:

  concoct \
       \
      --threads 2 \
      --coverage_file MEGAHIT-CONCOCT-CH10_R.tsv \
      --composition_file MEGAHIT-CONCOCT-CH10_R.fasta \
      -b MEGAHIT-CONCOCT-CH10_R

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BINNING:FASTA_BINNING_CONCOCT:CONCOCT_CONCOCT":
      concoct: $(echo $(concoct --version 2>&1) | sed 's/concoct //g' )
  END_VERSIONS

Command exit status:
  -

Command output:
  (empty)

Command error:
  222,-17922461.519941,15.102254
  223,-17922445.345640,16.174300
  224,-17922429.325022,16.020618
  225,-17922408.566563,20.758459
  226,-17922400.702804,7.863760
  227,-17922403.831180,3.128377
  228,-17922402.510138,1.321042
  229,-17922380.994748,21.515390
  230,-17922365.637246,15.357503
  231,-17922331.215201,34.422045
  232,-17922269.367195,61.848006
  233,-17922228.400540,40.966655
  234,-17922187.512440,40.888099
  235,-17922181.128473,6.383967
  236,-17922176.976471,4.152002
  237,-17922159.433939,17.542532
  238,-17922143.128578,16.305360
  239,-17922122.733958,20.394621
  240,-17922112.740287,9.993671
  241,-17922105.813026,6.927261
  242,-17922082.522069,23.290957
  243,-17922064.156071,18.365998
  244,-17922054.141601,10.014470
  245,-17922049.517194,4.624407
  246,-17922045.343921,4.173273
  247,-17922015.961686,29.382235
  248,-17921995.230892,20.730794
  249,-17921985.794146,9.436745
  250,-17921976.794194,8.999952
  251,-17921972.655531,4.138663
  252,-17921975.602384,2.946853
  253,-17921939.220422,36.381963
  254,-17921889.417897,49.802524
  255,-17921870.541204,18.876693
  256,-17921868.778457,1.762747
  257,-17921861.711391,7.067066
  258,-17921851.587287,10.124104
  259,-17921841.174210,10.413077
  260,-17921817.046927,24.127283
  261,-17921784.631202,32.415725
  262,-17921749.328024,35.303178
  263,-17921716.517976,32.810048
  264,-17921697.516007,19.001969
  265,-17921689.275145,8.240863
  266,-17921683.214387,6.060757
  267,-17921680.248196,2.966191
  268,-17921669.310317,10.937879
  269,-17921645.850906,23.459411
  270,-17921641.159293,4.691612
  271,-17921633.740619,7.418674

Work dir:
  /gpfs1/work/bonatell/work/56/402b448993b725fd76237c8688f149

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`


Join mismatch for the following entries:
- key=[id:CH10_R, group:0, single_end:false, assembler:MEGAHIT, binner:CONCOCT] values=[/gpfs1/work/bonatell/work/48/3e519cf2d76e21f093b426e86de4fb/MEGAHIT-CH10_R.contigs.fa]
- key=[id:CH10_R, group:0, single_end:false, assembler:SPAdes, binner:CONCOCT] values=[/gpfs1/work/bonatell/work/c8/adc81233b49ffd3fc782d4df2da98d/SPAdes-CH10_R_scaffolds.fasta]


Join mismatch for the following entries:
- key=SPAdes-MaxBin2-CH10_R.012.fa values=
- key=MEGAHIT-MaxBin2-CH10_R.017.fa values=
- key=MEGAHIT-MetaBAT2-CH10_R.15.fa values=
- key=MEGAHIT-MetaBAT2-CH10_R.21.fa values=
- key=SPAdes-MetaBAT2-CH10_R.10.fa values=
- key=SPAdes-MetaBAT2-CH10_R.18.fa values=
- key=MEGAHIT-MaxBin2-CH10_R.023.fa values=
- key=SPAdes-MetaBAT2-CH10_R.9.fa values=
- key=SPAdes-MaxBin2-CH10_R.006.fa values=
- key=MEGAHIT-MetaBAT2-CH10_R.29.fa values=
(more omitted)


Should I try to run for more time and with more memory, or this might be a bug?
My files are around 8.6 Gb of size (when uncompressed).

Thank you again!

**Comment by d4straub** [comment]
> Caused by:
> Process exceeded running time limit (12h)

I'd say more cpus to increase the speed and more time, a little more memory also doesnt hurt. I do not know how much though. I'd use a complete small node of our hpc for this, e.g. 20 cpus and 64GB RAM, and max time allowed. But only because I can, you might want to be more careful, depending on where you run your analysis.

**Comment by mlbonatelli** [comment]
I increase time and memory and it worked! Thanks! I am closing the issue now!
