### ISSUE TITLE
Feature can added to the MAG pipeline

### ISSUE THREAD

**Issue by mathavanpu** [nf-core/mag#425]
### Description of feature

Hi
I would like to suggest that the following feature can be added 

- Gene abundance analysis (the depth value of each contigs) 
- Secondary metabolite identification
- Antimicrobial gene prediction ( ResFinder, AmrFinderplus or fargene)
- Species abundance plot ( may in a pie diagram)

separate pipeline for 
fungal and lower  eukaryotes genome annotation

**Comment by jfy133** [comment]
Hi @mathavanpu 

1. Depth value of each contig already exists, e.g.: https://nf-co.re/mag/results#mag/results-c9468cb9154402c4a4cab78664ee50c24a91f6c3/GenomeBinning/depths/contigs/
2. Please see [nf-core/funcscan](https://nf-co.re/funcscan)
3. Please see [nf-core/funcscan](https://nf-co.re/funcscan)
4. nf-core/mag already has Krona plots, or do you mean for the number of contigs?

Separate pipeline:

There have been suggestions for this already, please see - https://github.com/nf-core/mag/issues/388 and provide any further feedback there
