### ISSUE TITLE
Entry point to pipeline at binning stage

### ISSUE THREAD

**Issue by prototaxites** [nf-core/mag#431]
### Description of feature

Assembly can be a time and resource-intensive process, and if returning to an old pipeline run (or using an assembly supplied by someone else), it would be useful to be able to skip the assembly stage altogether and use existing files. This would allow users to use the updated binning workflows from newer versions of the pipeline on assemblies generated in older pipeline runs.

Could implement this by allowing the user to supply a CSV of assemblies to the pipeline, as well as the standard input sheet which should contain the reads (post-QC, host removal, etc.) that were used to build the assemblies. The assembly CSV should have a group field which should match with the group identifiers listed in the reads sheet.

**Comment by artur-matysik** [comment]
It would be fantastic to have this! 

As a quick and dirty workaround I was using something like:
- added `params.assembly_done`. If true, workflow is expecting `params.inputAssemblies`
- assembly enclosed in `if (!params.assembly_done) { ... }`
- and if assembly is done already (`else {...}`) assemblies channels `ch_assemblies` is defined as below, using provided
`params.inputAssemblies`

```
// Extract sample ID
        def get_id = { it ->
            def startDelimiter = it.split("-")[0] + "-"
            def endDelimiter = "_scaffolds.fasta"
            def startIndex = it.indexOf(startDelimiter) + startDelimiter.length()
            def endIndex = it.indexOf(endDelimiter)
            def result = it.substring(startIndex, endIndex)
            return result
        }
    
        ch_assemblies = Channel
            .fromPath(params.inputAssemblies)
            .map { row -> tuple ( row.getBaseName(), row )} 
            .map { row -> tuple ( [id: get_id(row[0]), group: 0, single_end: false, assembler: row[0].split("-")[0]], row[1] ) }
```
