### ISSUE TITLE
terminated with exit status 255 at GUNZIP BINS singularity

### ISSUE THREAD

**Issue by aquaiser** [nf-core/mag#443]
Hello,
I have issues to run the complete pipeline. Using singularity I get most often the error indicated. I downloaded the pipeline, the singularity images and defined the singularity cache. I set the cpu per task to 20 (tried also 10) and mem 100G. I also tried profile singularity as well as profile of our server. It's not only this error, but I never succeeded to get beyoind this step.

Thanks for your help

Achim

here is my script:
#! /bin/bash
#SBATCH --cpus-per-task=10
#SBATCH --mem=100G
#SBATCH --time=09:00:00

. /softs/local/env/envnextflow-22.10.4.sh

nextflow run nf-core/mag -profile singularity --input '/scratch/aquaiser/mB1_mS12_mag_contigs_input.csv' --outdir out_mag_mB12_mS1_plus_contigs

**Comment by jfy133** [comment]
@aquaiser please provide the actual error and ideally the `.nextflow.log` file. Unfortunately your original post does not have enough information for us to help you.

As a side note, I'm I wondering if you are correctly using Nextflow in the most optimal manner. If you are working on a SLURM cluster (I presume, based on the SBATCH headers), you will want Nextflow to be doing job submission across the cluster nodes for you - rather than having to run all your jobs on a single node with a very large job request. 

If there is not a specific reason why you are doing it like this, I would highly recommend looking at the Nextflow ([here](https://www.nextflow.io/docs/latest/executor.html#slurm) and [here](https://www.nextflow.io/docs/latest/config.html#scope-executor) and [nf-core documentation](https://nf-co.re/docs/usage/configuration#running-nextflow-on-your-system) on how to make a configuration file that will tell Nextflow to submit jobs for you using SLURM. You can also see many different examples on [nf-core/configs](https://github.com/nf-core/configs/tree/master/conf)

**Comment by aquaiser** [comment]
Hello,
Yes it's slurm. I tried again with - profile genouest. If I understand well this indicates that I use the preconfigured nextflow config file from our servers. This should handle the nodes ?
Attached the nextflow.log and the slurm output with the error.

Thanks for your help
Best
Achim

[nextflow.log](https://github.com/nf-core/mag/files/11480532/nextflow.log)
[slurm_output.txt](https://github.com/nf-core/mag/files/11480543/slurm_output.txt)

**Comment by jfy133** [comment]
Hi Achim,

Yes if that's the cluster you're working on that should get you going (you may need furhter optimisation for the pipeline itself, but that would be a good start).

Your actually error was:

```
Caused by:
  Process `NFCORE_MAG:MAG:BINNING:GUNZIP_BINS (MEGAHIT-CONCOCT-mS2_133.fa.gz)` terminated with an error exit status (2)

Command executed:

  gunzip \
      -f \
       \
      MEGAHIT-CONCOCT-mS2_133.fa.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BINNING:GUNZIP_BINS":
      gunzip: $(echo $(gunzip --version 2>&1) | sed 's/^.*(gzip) //; s/ Copyright.*$//')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  WARNING: failed to read passwd file content in container: read /var/apptainer/mnt/session/rootfs/etc/passwd: input/output error
  WARNING: failed to read group file content in container: read /var/apptainer/mnt/session/rootfs/etc/group: input/output error
  fatal error: unexpected signal during runtime execution
  [signal SIGBUS: bus error code=0x2 addr=0x7f0c0451f000 pc=0x7f0c0450e4da]
  
  runtime stack:
  runtime.throw({0x55f41d71e0bb, 0x0})
  	runtime/panic.go:1198 +0x71
  runtime.sigpanic()
  	runtime/signal_unix.go:719 +0x396
  
  goroutine 1 [syscall, locked to thread]:
  runtime.cgocall(0x55f41d6f4020, 0xc000117588)
  	runtime/cgocall.go:156 +0x5c fp=0xc000117560 sp=0xc000117528 pc=0x55f41d1594bc
  crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL()
  	_cgo_gotypes.go:603 +0x4d fp=0xc000117588 sp=0xc000117560 pc=0x55f41d3253ed
  crypto/internal/boring.init.0()
  	crypto/internal/boring/boring.go:46 +0x45 fp=0xc0001175c0 sp=0xc000117588 pc=0x55f41d32cd25
  runtime.doInit(0x55f41defde60)
  	runtime/proc.go:6498 +0x125 fp=0xc0001176f8 sp=0xc0001175c0 pc=0x55f41d19abe5
  runtime.doInit(0x55f41defd1a0)
  	runtime/proc.go:6475 +0x71 fp=0xc000117830 sp=0xc0001176f8 pc=0x55f41d19ab31
  runtime.doInit(0x55f41df02e00)
  	runtime/proc.go:6475 +0x71 fp=0xc000117968 sp=0xc000117830 pc=0x55f41d19ab31
  runtime.doInit(0x55f41df03220)
  	runtime/proc.go:6475 +0x71 fp=0xc000117aa0 sp=0xc000117968 pc=0x55f41d19ab31
  runtime.doInit(0x55f41defe720)
  	runtime/proc.go:6475 +0x71 fp=0xc000117bd8 sp=0xc000117aa0 pc=0x55f41d19ab31
  runtime.doInit(0x55f41defc6a0)
  	runtime/proc.go:6475 +0x71 fp=0xc000117d10 sp=0xc000117bd8 pc=0x55f41d19ab31
  runtime.doInit(0x55f41defe2c0)
  	runtime/proc.go:6475 +0x71 fp=0xc000117e48 sp=0xc000117d10 pc=0x55f41d19ab31
  runtime.doInit(0x55f41defcaa0)
  	runtime/proc.go:6475 +0x71 fp=0xc000117f80 sp=0xc000117e48 pc=0x55f41d19ab31
  runtime.main()
  	runtime/proc.go:238 +0x1e6 fp=0xc000117fe0 sp=0xc000117f80 pc=0x55f41d18d806
  runtime.goexit()
  	runtime/asm_amd64.s:1581 +0x1 fp=0xc000117fe8 sp=0xc000117fe0 pc=0x55f41d1bcf01

Work dir:
  /scratch/aquaiser/work/a0/614b7d4e7bef31a04d4ea095b37380
  ```
  
This is a very unusal error to see for a Nextflow pipeline and to me it suggests a node or something died, I think. It may also be a memory issue, (Although that would bestrange for GUNZIP). I wonder if you were overloading your particular node as you were running the whole pipeline on one rahte rthan submitting to slurm (again would be unlikely, but I Can't think of any other reason at the moment).

You said this is the most common errors, what else have you been getting? But I think if you try with the genoouest profile hopefully it'll be fixed. 

If the errors come up again, you can reopen this issue and we can look more deeply :)
