### ISSUE TITLE
Host removal parameter - pre-built bowtie2 index

### ISSUE THREAD

**Issue by simone-pignotti** [nf-core/mag#452]
### Description of feature

Hi,

In the host removal module, the bowtie index needs to be recomputed from `--host_fasta` for each execution.
Would it be possible to add `--host_bt2` or similar to point to a pre-built index prefix? The logic is already implemented for the `--host_genome` option, where pre-built indexes from iGenomes are used.

Thanks
Simone

**Comment by hkaspersen** [comment]
Hello! I second this, the host genomes I use are quite big, and by having this option it will significantly reduce runtime of the pipeline

**Comment by Thomieh73** [comment]
@jfy133 hey, is this idea already implemented. I am trying to run it with a large host genome file, and I get the error that bowtie build needs the setting: --large-index. I already have a prebuild index for Bowtie, so if this option is available than I rather use that.

**Comment by jfy133** [comment]
Hi @Thomieh73 

Sorry not yet, the request just came before I started parental leave and slipped through the cracks...

But I'm almost at the end of my leave and ramping up work again, so barring any other interruptions I can try and do this soon

**Comment by Thomieh73** [comment]
Okay, I can understand that. I am trying figure out a work around in the meantime. With the Taxprofiler pipeline, I used my bowtie host genome index, and I cleaned the files then. I could use those cleaned files with this pipeline.

**Comment by jfy133** [comment]
yes, that's a good idea :)
