### ISSUE TITLE
Error executing process > 'NFCORE_MAG:MAG:QUAST_BINS (SPAdes-MaxBin2-test_minigut_sample2)'

### ISSUE THREAD

**Issue by msubirana** [nf-core/mag#457]
### Description of the bug

Running the initial example I got the following error. I have installed singularity and nextflow as described in the doc.

### Command used and terminal output

```console
nextflow run nf-core/mag -profile test,singularity --outdir .


Error executing process > 'NFCORE_MAG:MAG:QUAST_BINS (SPAdes-MaxBin2-test_minigut_sample2)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-quast-5.0.2--py37pl526hb5aa323_2.img.pulling.1686730650200 https://depot.galaxyproject.org/singularity/quast:5.0.2--py37pl526hb5aa323_2 > /dev/null
  status : 143
  message:
    INFO:    Downloading network image
```

### System information

nextflow version 22.10.7.5853
ubuntu 22.04
singularity 3.6.3

**Comment by d4straub** [comment]
Well, the singularity image was not able to be pulled. This might be connectivity issues, the container is accessible with https://depot.galaxyproject.org/singularity/quast:5.0.2--py37pl526hb5aa323_2 (just tested). Resume the pipeline (add `-resume` to your command).
