### ISSUE TITLE
memory allocation fails

### ISSUE THREAD

**Issue by mtva0001** [nf-core/mag#466]
### Description of the bug

I'm running the mag (2.3.2) pipeline in conda environment on our own server and the SPAdes process failes due to: "Reason: Cannot allocate memory. Error code: 12". It runs the command with only 64 GB memory, although I clearly specified in the nextflow command that I want to have max 200 GB memory.

How can I solve this without creating a custom config file? 

### Command used and terminal output

```console
nextflow run nf-core/mag -profile conda --input test_sample.csv --outdir result_test -bg -resume small_leakey --max_memory '200.GB' --gtdb 'https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz' --kraken2_db 'ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/minikraken_8GB_202003.tgz'
```

### Relevant files

[spades.log](https://github.com/nf-core/mag/files/11915737/spades.log)

### System information

[condalist.txt](https://github.com/nf-core/mag/files/11915754/condalist.txt)

**Comment by jfy133** [comment]
Hi @mtva0001 `--max_memory` does not increase memory, it is only a maximum 'cap' it is allowed a pipeline step is allowed to reach.

Please see https://nf-co.re/docs/usage/configuration#max-resources on more information on that, and then the section after on how to increase the memory :)

**Comment by jfy133** [comment]
> How can I solve this without creating a custom config file?

Unfortunately you can't, you must use one

**Comment by mtva0001** [comment]
Thanks for the quick response! Okay, so I should use the 'Advanced option' and modify this small script:
process {
    withName: 'NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN' {
        memory = 100.GB
    }
}

Why is nf-core/rnaseq referred in the mag pipeline documentation? You provide link to many github pages but it is not clear where I could find the exact process name for SPAdes that I should use in a custom config file. 

Anyway, since nf-core was created to help people with very limited bioinformatic skills and to process sequences without thinking of any specific steps, wouldn't it be possible to create a tag option instead of forcing us to modify/create config files?

**Comment by d4straub** [comment]
> Anyway, since nf-core was created to help people with very limited bioinformatic skills and to process sequences without thinking of any specific steps, wouldn't it be possible to create a tag option instead of forcing us to modify/create config files?

Sorry, but using a simple text file is not bioinformatics. When you aim to do something complicated like metagenome assembly, in my opinion, it can be expected that you spend some time with files. You get it a little wrong here, we are not working for you, but for people who are engaged in the community and give also something back, not only take our time and investment.

Metagenome assembly isnt possible with a one-fits-it-all config, especially with resources. Its unpredictable. We can catch many cases, but (in my limited experience as the original creator of the pipeline) not even most. In my experience, metagenome assembly is by far more complicated than most other analysis (mapping-based genomics, amplicon seq, rna seq, ...).

**Comment by jfy133** [comment]
> Thanks for the quick response! Okay, so I should use the 'Advanced option' and modify this small script:
> process {
>     withName: 'NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN' {
>         memory = 100.GB
>     }
> }

Yes, you can just change the name of the process you want to increase

> 
> Why is nf-core/rnaseq referred in the mag pipeline documentation? You provide link to many github pages but it is not clear where I could find the exact process name for SPAdes that I should use in a custom config file. 

It is a boilerplate across all nf-core pipelines, to ensure consistency and familiarity across all pipelines, the RNASEQ pipeline is the most popular and thus used as generic examples everywhere. 

But the concept exactly the same regardless of the pipeline so we have found that most people have been able to infer this quite easily, as you get the process name right at the top of the error.


If you found it confusing you are welcome to suggest changing it - please make an issue in https://github.com/nf-core/tools


> Anyway, since nf-core was created to help people with very limited bioinformatic skills and to process sequences without thinking of any specific steps, wouldn't it be possible to create a tag option instead of forcing us to modify/create config files?

I sort of agree here with @d4straub , I think it's a naive assumption that anything in bioinformatics is just running blindly.

Any complex bioinformatic pipeline is indeed very daunting, so nf-core does help with much of this with its infrastructure. But I don't think any pipeline is for anyone with very limited bioinformatics experience - there are too many moving parts and biases you should be aware of.

One such helpful thing  is nf-core/configs that are centralised configuration files for institutional HPCs, that does help people to run without having to do things such as # resource configurations (you supply only `-profile <institute>`), adapted to the common data types of that institution.

This does require investment in initial set up, but then for all users of the particular cluster life is much easier. This is the same thing for running on a laptop: you generally just need to make the config once and don't have to touch it again, so this shouldn't be that arduous.

Specifically with tags, it would be nice but can you suggest how we could reasonably do this for a pipeline with >40 processes/steps? Adding an extra 40 parameters to the pipeline would not be very user friendly e.g. when it comes to help messages etc.

Thus the investment in  config files (which Indeed are complex, but extremely powerful!)

**Comment by jfy133** [comment]
Oh, and if you're interested in creating a Institutional config please let us know! We are very happy to assist people in creating and testing them - please join the nf-core slack and  ask in #configs :)

**Comment by mtva0001** [comment]
Many thanks @jfy133 !
