### ISSUE TITLE
BUSCO error: `Either --summaries_domain, --summaries_specific or --failed_bins must be specified!`

### ISSUE THREAD

**Issue by bioforkgithub** [nf-core/mag#468]
### Description of the bug

I have downloaded the BUSCO datadase and whenever i give the local path to the folder this is the error i get

### Command used and terminal output

```console
[nf-core/mag] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_MAG:MAG:BUSCO_QC:BUSCO_SUMMARY'

Caused by:
  Process `NFCORE_MAG:MAG:BUSCO_QC:BUSCO_SUMMARY` terminated with an error exit status (1)

Command executed:

  summary_busco.py -a    -o busco_summary.tsv

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BUSCO_QC:BUSCO_SUMMARY":
      python: $(python --version 2>&1 | sed 's/Python //g')
      pandas: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('pandas').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  Either --summaries_domain, --summaries_specific or --failed_bins must be specified!
  INFO:    Cleaning up image...

Work dir:
  /gpfs/gpfs0/prosjekt/.prosjekt2/15719-Res-Marine/workingspace/sra_data/_13_svalbard/sample9/S9R2/Sample_18-WWR2/work/84/ae5bf0208b290098b73fe10dace310

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### Relevant files

Jul-04 13:18:56.561 [main] DEBUG nextflow.cli.Launcher - $> nextflow run /localsoftware/nf-core-mag_2.3.2/2_3_2/ -profile singularity --input samples.csv --outdir nf-core_result --multiqc_title MULTIQC --centrifuge_db /gpfs/gpfs0/felles/fres/MY_CENTRIFUGE_DB/hpvc.tar.gz --skip_spades --skip_spadeshybrid --busco_clean --refine_bins_dastool --ancient_dna true
Jul-04 13:18:56.633 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.1
Jul-04 13:18:56.650 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/a40540/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.2
Jul-04 13:18:56.659 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-04 13:18:56.659 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-04 13:18:56.663 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-04 13:18:56.673 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-04 13:18:57.541 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /localsoftware/nf-core-mag_2.3.2/2_3_2/nextflow.config
Jul-04 13:18:57.542 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /localsoftware/nf-core-mag_2.3.2/2_3_2/nextflow.config
Jul-04 13:18:57.549 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jul-04 13:18:58.375 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, alice, mjolnir_globe, uppmax, incliva, uge, rosalind_uge, lugh, unibe_ibu, vai, czbiohub_aws, jax, ccga_med, scw, tigem, tubingen_apg, google, ipop_up, googlels, eddie, medair, test_host_rm, bi, bigpurple, sbc_sharc, adcra, cedars, vsc_kul_uhasselt, pawsey_nimbus, ucl_myriad, utd_ganymede, charliecloud, icr_davros, test_ancient_dna, ceres, munin, arm, rosalind, test_binrefinement, hasta, cfc, uzh, test_hybrid_host_rm, test_busco_auto, ebc, ku_sund_dangpu, ccga_dx, test_hybrid, crick, marvin, biohpc_gen, shifter, mana, mamba, wehi, awsbatch, imperial, maestro, genotoul, test_no_clipping, abims, janelia, nihbiowulf, nu_genomics, googlebatch, oist, sahmri, mpcdf, leicester, vsc_ugent, sage, cambridge, podman, cheaha, xanadu, test, computerome, seg_globe, sanger, dkfz, pasteur, test_full, azurebatch, hki, test_adapterremoval, crukmi, docker, engaging, gis, hypatia, psmn, eva, fgcz, conda, crg, singularity, prince, utd_sysbio, debug, genouest, cbe, phoenix, gitpod, seawulf, uct_hpc, aws_tower, binac]
Jul-04 13:18:58.412 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Jul-04 13:18:58.425 [main] INFO  nextflow.cli.CmdRun - Launching `/localsoftware/nf-core-mag_2.3.2/2_3_2/main.nf` [big_saha] DSL2 - revision: 8f9adbafb4
Jul-04 13:18:58.426 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-04 13:18:58.426 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jul-04 13:18:58.432 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/a40540/.nextflow/secrets/store.json
Jul-04 13:18:58.434 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@b01cb8d] - activable => nextflow.secret.LocalSecretsProvider@b01cb8d
Jul-04 13:18:58.479 [main] DEBUG nextflow.Session - Session UUID: baa2de72-89e8-4e96-ae9d-ca332d62785f
Jul-04 13:18:58.479 [main] DEBUG nextflow.Session - Run name: big_saha
Jul-04 13:18:58.480 [main] DEBUG nextflow.Session - Executor pool size: 256
Jul-04 13:18:58.489 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=768; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jul-04 13:18:58.511 [main] DEBUG nextflow.cli.CmdRun -
  Version: 23.04.1 build 5866
  Created: 15-04-2023 06:51 UTC (08:51 CEST)
".nextflow.log" 505L, 88501B                     

### System information

Nextflow version ( 23.04.1)
Hardware (local server)
Executor (local)
Container engine: (Singularity)
OS (CentOS)
Version of nf-core/mag (2.3.2)

**Comment by jfy133** [comment]
@bioforkgithub could you please provide the actual `.nextflow.log` file? 

I see you're running aDNA mode, from the limit logging information, my only thought is if none enough bins were generated for binning refinement (meaning the BUSCO filesweren't generated and couldn't reach the BUSCO summary)

I see you are running a local physical copy of the pipeline (` /localsoftware/nf-core-mag_2.3.2/2_3_2/`) rather than using the official `nextflow pull nf-core/mag -r 2.3.2` can you confirm you've not modified this in any way?

**Comment by bioforkgithub** [comment]
/localsoftware/nf-core-mag_2.3.2/2_3_2/ . here the localsoftware is the name of my drive where I usually save all the git downloads. Ok I will check for busco because even though I am changing it to run checkm, busco is running is always showing up.
No i havent changes any files after download. And ihave followed the instructions on the github about the installation.

**Comment by jfy133** [comment]
@bioforkgithub Ok... not sure I follow as you're meant to get nextflow pipeliens with `nextflow pull` which then pulls to `$NXF_HOME/assets/nf-core/<pipeline>` - you shouldn't really `git clone` nextflow pipelines (even if you technically you can), but fair enough if you've not changed anything.

The `relevant file` section above isn't the actual file - you've just pasted the first X number of lines (from a terminal editor like `vim` by the looks of it?), so if you could upload the actual `.nextflow.log` file I should have all the info I need.

**Comment by bioforkgithub** [comment]
Maybe there was an issue with my system. It worked on my friends system. Thankyou.
