### ISSUE TITLE
Add option to export BAM file with reads aligned against the contigs to results folder

### ISSUE THREAD

**Issue by alexhbnr** [nf-core/mag#487]
### Description of feature

Currently, nf-core/mag will keep the BAM files that resulted from aligning the short-read data against the assembled contigs using BowTie2 in the temporary `work` directory. However, for some subsequent analyses it might be helpful to keep these files for later. Therefore, an option to save these files into the `results` directory would be great.

**Comment by d4straub** [comment]
That should be possible via a config. Thats tedious of course. If thats a more regular task then I agree to add a parameter to save  bowtie bam files on request in the results folder.
