### ISSUE TITLE
Issues running testprofile. "BUSCO analysis failed for some unknown reason!"

### ISSUE THREAD

**Issue by CEJ-R** [nf-core/mag#490]
### Description of the bug

Running the pipeline with the 'test' profile results in pipeline terminating prematurely due to `ERROR: BUSCO analysis failed for some unknown reason! See also SPAdes-MetaBAT2-test_minigut.2.fa_busco.err.`, which is an error I'm having a hard time interpreting.
There's also an instance of ``NFCORE_MAG:MAG:BINNING:MAXBIN2 (test_minigut_sample2)`` that fails, but this might be as intended with your testcase, as it doesn't kill the rest of the workflow?

### Command used and terminal output

```console
nextflow run /project_dir/nf-core-mag-2.3.2/workflow/ \
-profile test,singularity \
--checkm_db /project_dir/Data/check_m_database \
--outdir /project_dir/Results/first_test_results
```

### Relevant files
[nextflow.log](https://github.com/nf-core/mag/files/12303540/nextflow.log)

### System information

Nextflow: 23.02.0-edge build 5838
System: Linux 4.18.0-425.13.1.el8_7.x86_64
Pipeline version: nf-core/mag v2.3.2
Container: Singularity

**Comment by jfy133** [comment]
(writing from my phone) the maxxbin2 failure is to be expected!

**Comment by jfy133** [comment]
For the main error, you'll need to look in the file it says, which should be in:

```
/project_dir/Code/work/b6/64007507ed0bae8113b68edd527281```

The current error message Indeed is not helpful but has been made better in current `dev` version

**Comment by jfy133** [comment]
Yes! https://nf-co.re/mag/2.3.2/parameters#busco_download_path

**Comment by jfy133** [comment]
I assume that was the issue so will close now
