### ISSUE TITLE
Allow decompressed databases to be used for gtdb, kraken2, centrifuge, and busco

### ISSUE THREAD

**Issue by gregorysprenger** [nf-core/mag#498]
### Description of feature

Current behavior:
nf-core/mag requires compressed database files to be passed to it for gtdb, kraken2, centrifuge, and busco. This requires the pipeline to decompress these files and adds computation time. (follow up to [#148](https://github.com/nf-core/mag/issues/148)) 

Expected behavior:
Have the pipeline automatically detect if the database is or needs to be decompressed. For shared compute resources, databases are typically decompressed for multiple users to run tools.

**Comment by jfy133** [comment]
Hi @gregorysprenger ! We've started this already e.g., https://github.com/nf-core/mag/pull/477, but it would be indeed useful to have all of these. Lets have a checklist here:

- [x] gtdb
- [ ] kraken2
- [ ] centrifuge
- [ ] busco

**Comment by jfy133** [comment]
Done, thanks @gregorysprenger !
