### ISSUE TITLE
GUNC output overwriting itself

### ISSUE THREAD

**Issue by maxibor** [nf-core/mag#502]
### Description of the bug

Gunc outputs are being overwritten is the result directory: the output file name of gunc is `GUNC.{DB version}maxCSS_level.tsv` and `{PREFIX}.all_levels.tsv`. (see [GUNC doc](https://grp-bork.embl-community.io/gunc/output.html#output-files))

Because GUNC is run per bin in nf-core/mag, but the results are saved per `[assembler]-[binner]-[sample]` (See code [here](https://github.com/maxibor/mag/blob/49474625c1b46eb5ab16a6a7dc00e38e6cb7e0cc/conf/modules.config#L422-L423)) (and should probably be `[assembler]-[binner]-[domain]-[refinement]-[sample]` according to #489 ) and are therefore being overwritten.

Note that the gunc summary is not affected, and the `gunc_summary.tsv` file is fine.

**Comment by jfy133** [comment]
Personal i.e., once #489, have a second PR to update the `prefix`.

Note we should also possible update `prefix` PROKKA which may also have the same problem.
