### ISSUE TITLE
MaxBin2 bins missing from GenomeBinning/MaxBin2/bins

### ISSUE THREAD

**Issue by Perugolate** [nf-core/mag#503]
### Description of the bug

`GenomeBinning/bin_summary.tsv` lists a mix of MetaBAT2 and MaxBin2 bins. `GenomeBinning/MetaBAT2/bins/` seems to contain the listed MetaBAT2 bins but I can't locate the MaxBin2 bins, `GenomeBinning/MaxBin2/bins` is empty.

### Command used and terminal output

```console
nextflow run nf-core/mag --input samplesheet.csv -profile singularity --outdir /mnt/shared/scratch/pjohnsto/20230828_nfc_mag_soil_amr_full/ --skip_spades true --busco_reference /mnt/shared/scratch/pjohnsto/db/bacteria_odb10.2020-03-06.tar.gz --save_busco_reference --skip_concoct true -resume
```

### System information

N E X T F L O W  ~  version 23.04.3
HPC
slurm
apptainer 1.2.2-1.el8
rocky linux 8.8
nf-core/mag v2.3.2-g66cf53a

**Comment by jfy133** [comment]
Fixed in https://github.com/nf-core/mag/pull/500
