### ISSUE TITLE
Error with SPAdes (Exit status 250)

### ISSUE THREAD

**Issue by s-junguy** [nf-core/mag#506]
### Description of the bug

Hi, I've got an issue with SPAdes. I tested the pipeline on one Illumina paired end library (10 GB). 
This is my submission script:
#!/bin/bash
#SBATCH --cpus-per-task=15
#SBATCH --time=72:00:00
#SBATCH --partition=snowball
#SBATCH --ntasks=1
#SBATCH -o mag.%j.%N.out
#SBATCH -e mag.%j.%N.err
module load singularity
nextflow run nf-core/mag --input samples.csv --outdir /home/usr/magoutsamples -profile singularity

### Command used and terminal output

```console
$ nextflow run nf-core/mag --input samples.csv --outdir /home/usr/magoutsamples -profile singularity


ERROR ~ Error executing process > 'NFCORE_MAG:MAG:SPADES (sample1)'

Caused by:
  Process `NFCORE_MAG:MAG:SPADES (sample1)` terminated with an error exit status (250)

Command executed:

  metaspades.py                          --threads "16"             --memory 128             --pe1-1 sample1.phix_removed.unmapped_1.fastq.gz             --pe1-2 sample1.phix_removed.unmapped_2.fastq.gz             -o spades
  mv spades/assembly_graph_with_scaffolds.gfa SPAdes-sample1_graph.gfa
  mv spades/scaffolds.fasta SPAdes-sample1_scaffolds.fasta
  mv spades/contigs.fasta SPAdes-sample1_contigs.fasta
  mv spades/spades.log SPAdes-sample1.log
  gzip "SPAdes-sample1_contigs.fasta"
  gzip "SPAdes-sample1_graph.gfa"
  gzip -c "SPAdes-sample1_scaffolds.fasta" > "SPAdes-sample1_scaffolds.fasta.gz"

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:SPADES":
      python: $(python --version 2>&1 | sed 's/Python //g')
      metaspades: $(metaspades.py --version | sed "s/SPAdes genome assembler v//; s/ \[.*//")
  END_VERSIONS

Command exit status:
  250

 == Error ==  system call for: "['/usr/local/bin/spades-hammer', 'spades/corrected/configs/config.info']" finished abnormally, OS return value: -6
```

**Comment by jfy133** [comment]
This is an issue with SPAdes rather than nf-core/mag specifically.

In most cases such errors are due to insufficient memory (unfortunately error reporting by SPAdes is not great).

To increase the memory you will need do this via a custom config. See the nf-core documentation on how to do this [here](https://nf-co.re/docs/usage/configuration#tuning-workflow-resources)
