### ISSUE TITLE
CONCOCT missing in globs in downstream processes of modules.conf

### ISSUE THREAD

**Issue by jfy133** [nf-core/mag#510]
### Description of the bug

As reported by @maxibor  privately

**Comment by maxibor** [comment]
TLDR:

https://github.com/nf-core/mag/blob/66cf53aff834d2a254b78b94fc54cd656b8b7b57/conf/modules.config#L648C20-L648C20 needs Concoct as well

```withName: DASTOOL_FASTATOCONTIG2BIN_CONCOCT {
        ext.prefix = { "${meta.assembler}-CONCOCT-${meta.id}" }
    }
``` 
needs to be added in modules.config
