### ISSUE TITLE
MetaBAT2 bins folder not created, and MAGs from metabat2 not saved. 

### ISSUE THREAD

**Issue by patriciatran** [nf-core/mag#531]
### Description of the bug

I can see from my CheckM & QUAST output that there are good quality METABAT2 bins, (`results > GenomeBinning > QC > CheckM > checkm_summary.tsv`), however my` Genome Assembly > MetaBAT2` folder always only contains the `unbinned` and discard folders. Whereas the `MaxBin2` folder contains `unbinned`, `bins`, and `discarded`. Here is an example of what I mean.

![Screenshot 2023-11-02 at 11 08 28 AM](https://github.com/nf-core/mag/assets/16926887/b58a938b-a3aa-438e-acc0-36d2d6be5a1c)

This happens with all the samples I ran so far. I’m using the tar.gz file from the 2.5.0 release.

In other words, it’s not making this file: `bins/[assembler]-[binner]-[sample/group].*.fa.gz` nor the `bins` folder under `MetaBAT2` (https://nf-co.re/mag/2.5.0/docs/output#binning-and-binning-refinement)

There might be an issue with "the glob pattern we use when 'publishing' the files". 

Thank you!

### Command used and terminal output

```console
nextflow run main.nf -profile singularity -c copy_custom_res.conf --input group_samples_fastq_paths_sub.csv --outdir results_2 --email [my_email] --skip_spadeshybrid true --skip_megahit true --skip_concoct true --skip_prokka true --refine_bins_dastool false --binqc_tool checkm --skip_gtdbtk true --max_cpus 20 --max_memory 250.GB
```

### System information

Nextflow version 23.10.0, build 5889 (15-10-2023 15:07 UTC)
Hardware HTCondor 
Local Executor
Container: Singularity
OS: Linux
nf-core/mag: 2.5.0 (https://github.com/nf-core/mag/releases/tag/2.5.0, downloaded the tar.gz file)

**Comment by jfy133** [comment]
I've found the bug. Indeed (as mentioned on slack) it was that MetaBAT2 makes nasty output file names which makes it hard to pick up using globs).

So I need to modify the module to make this easier, which I think it might be possible :+1:
