### ISSUE TITLE
Pipeline Execution Failure: MissingMethodException for LinkedList.getFileSystem in Nextflow 23.10.0

### ISSUE THREAD

**Issue by lennijusten** [nf-core/mag#536]
### Description of the bug

Encountering a `MissingMethodException` when executing the nf-core/mag pipeline, specifically related to the `java.util.LinkedList.getFileSystem()`.

### Steps to Reproduce
1. Command used to run the pipeline:
   ```nextflow run nf-core/mag -profile docker --input 'fastq_files/*.fastq.gz' --outdir mag-results```

### Program output
```
N E X T F L O W  ~  version 23.10.0
Launching `https://github.com/nf-core/mag` [mighty_carlsson] DSL2 - revision: ba72349594 [master]
ERROR ~ Unknown method invocation `getFileSystem` on LinkedList type

 -- Check '.nextflow/assets/nf-core/mag/main.nf' at line: 44 or '.nextflow.log' for more details
```  
Extract from .nextflow.log:
```
Nov-07 03:45:27.972 [main] DEBUG nextflow.Session - Session aborted -- Cause: No signature of method: java.util.LinkedList.getFileSystem() is applicable for argument types: () values: []
Nov-07 03:45:27.986 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: java.util.LinkedList.getFileSystem() is applicable for argument types: () values: []
``` 
Running with docker/test profiles worked:
```
nextflow run nf-core/mag -profile docker,test --outdir mag-test
```
### Environment
Java Version
```
openjdk version "11.0.20" 2023-07-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.20.0.8-1.amzn2.0.1) (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.20.0.8-1.amzn2.0.1) (build 11.0.20+8-LTS, mixed mode, sharing)
```
Nextflow version
```
version 23.10.0 build 5889
created 15-10-2023 15:07 UTC
```
System information
```
Linux ip-172-31-37-92.ec2.internal 5.10.198-187.748.amzn2.x86_64 #1 SMP Tue Oct 24 19:49:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by d4straub** [comment]
Thanks for the report. As far as I can see file input isnt supported any more but only sample sheets ending with "csv".

https://github.com/nf-core/mag/blob/ba7234959405b7a6df253d6d03158a7cde030c96/workflows/mag.nf#L18-L25

https://github.com/nf-core/mag/blob/ba7234959405b7a6df253d6d03158a7cde030c96/nextflow_schema.json#L15-L24

So I see two problems:
- documentation needs an update (delete direct fastq input section)
- make sure that the csv extension is indeed checked, because that seems to have not worked as expected

Conclusion, as fasr as I see, make a sample sheet as decribed in the docs and the pipeline should work just fine.

**Comment by jfy133** [comment]
Thanks to a team effort of @d4straub @mahesh-panchal @nvnieuwk we identified it to just a the problem with a mis-specified nextflow schema. So 'direct' inpout of FASTQ files is indeed still supported :+1: 

Fix incoming :)

**Comment by d4straub** [comment]
Nice work, but why you kept in #537 the code in https://github.com/nf-core/mag/blob/ba7234959405b7a6df253d6d03158a7cde030c96/workflows/mag.nf#L18-L25
I thought its not used, did I miss something?
What about https://github.com/nf-core/mag/blob/ba7234959405b7a6df253d6d03158a7cde030c96/workflows/mag.nf#L13-L16 that seems also dead code?

**Comment by jfy133** [comment]
So indeed `hasExtension` is not necessary anymore. The former still appears to be important, as that value might be use for the `initalise` function that has a bunch of QC checks.  But I would need more time to investigate that, so I'm a bit loathe to do this right now in my limited time.

However we should review if we can strip any of those QC checks out as indeed some should be covered by the `nextflow_schema.json`

I will make a new issue for this, and a PR removing hasExtension
