### ISSUE TITLE
BUSCO db placement files not found

### ISSUE THREAD

**Issue by lborcard** [nf-core/mag#545]
### Description of the bug

During the run we encountered many problems with the download (download would stop after a  few sucessful downloads) of the BUSCO db so we decided to download it and give as a path using the `--busco_db` params. Unfortunately it throws an error saying it cannot find the placement_files eventhough they are present in the work folder and in the original location. I tried to identify where this will be parsed but to no avail the busco.sh bash file is difficult to read.

### Command used and terminal output

```console
nextflow main.nf --input sampleworksheet.csv --outdir results_denis_complete --email loic.borcard@unibe.ch -profile singularity -resume --gtdb_db /storage/tmp/database_prep/gtdbk/gtdbtk_r214_data.tar.gz --busco_db /storage/tmp/database_prep/busco_prep/busco-data.ezlab.org/v5/data/
```

### Relevant files

error file:
```
023-11-29 17:01:11 ERROR:	Unable to run BUSCO placer in offline mode. Cannot find necessary placement files in /storage/analysis/RnD/lb21z855/nf-pipelines/nf-core-mag_2.5.1/2_5_1/work/5a/79ebb3980a5198bdd909e530c86dcc/data
2023-11-29 17:01:11 ERROR:	BUSCO analysis failed!
2023-11-29 17:01:11 ERROR:	Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

```

### System information

N E X T F L O W  ~  version 23.04.2
HPC 
local
Centos
version : nf-core/mag v2.5.1

**Comment by jfy133** [comment]
Sorry for the very late delay replying: most of the developers are in end of year crunch and/or parental leave (the latter including myself).

Thanks for the report, will try and check it out ASAP. The only thing I can think of from the tip of my head is there somehow a tool version/database mismatch, but would need to have someone to replicate

**Comment by jfy133** [comment]
@lborcard apparently there was a lot of changes with BUSCO and their downloads recently.

This is fixed here: https://github.com/nf-core/mag/pull/553/commits/c2f44fe8c5999142d34119220b6591475eb953f5

Speaking to @maxibor and @HadrienG they said BUSCO is quite fickle, and if you want to manually supply the database and you must install BUSCO itself yourself and use their downloading tool to get the database, did you do that? 

I will close this for now, but feel free to reopen if still not working.
