### ISSUE TITLE
process GTDBTK_CLASSIFYWF: glob in find command

### ISSUE THREAD

**Issue by muniheart** [nf-core/mag#547]
### Description of the bug

[Tag 2.5.1] File modules/nf-core/gtdbtk/classifywf/main.nf, line 64: The argument to option `-name` contains glob character '\*'.  Either '*' should be escaped or the argument should be quoted.

**Comment by jfy133** [comment]
Just to keep track: this maybe fixed in an upcoming PR

**Comment by jfy133** [comment]
OK is not fixed in an upcoming PR unfortuantely... @muniheart would you be willing to open a PR to fix this? Would likely be faster that way :)

**Comment by jfy133** [comment]
Fixed in https://github.com/nf-core/mag/pull/548/commits/629e6672fa7d143945760008622fef3c7c10d0f9

**Comment by jfy133** [comment]
and thanks @muniheart !
