### ISSUE TITLE
Output directory MEGAHIT already exists, please change the parameter -o to another value to avoid overwriting.

### ISSUE THREAD

**Issue by s-junguy** [nf-core/mag#560]
### Description of the bug

Hi, 
I use Illumina paired-end reads and got this error message ` megahit: Output directory MEGAHIT already exists, please change the parameter -o to another value to avoid overwriting.`. I do not know where to put the option -o or how to change it. 

I submitted `nextflow run nf-core/mag --input samples.csv --outdir /home/s-junguy/magall -profile singularity -c ~/.nextflow/config --coassemble_group true -resume`. 

I also tried `nextflow run nf-core/mag --input samples.csv --outdir /home/s-junguy/magall -profile singularity -c ~/.nextflow/config --coassemble_group true -resume --megahit_options="--continue -o out"` but then MEGAHIT starts from the beginning even though it had almost finished before. 

So my question is... how do I put the option -o in there so that the pipeline starts from where it broke off?

**Comment by jfy133** [comment]
Hi @s-junguy 

Which version of the pipelinare you running?

We fixed this exact problem recently: https://github.com/nf-core/mag/pull/516/files

**Comment by s-junguy** [comment]
I use v2.3.2. How can I update the latest version? I installed nextflow via the typical installation (not conda).

**Comment by jfy133** [comment]
To update the pipeline just run `nextflow pull nf-core/mag -r 2.5.1` (if it doesn't work first time, try without the `-r 2.5.1` and then try with it again). 2.5.2 is the current latest of version of the pipeline 

If you need to update nextflow too< run `nextflow self-update`

**Comment by s-junguy** [comment]
Thanks for your help! I already updated nextflow. If I execute `nextflow pull nf-core/mag` I get the message: `Checking nf-core/mag ...
nf-core/mag contains uncommitted changes -- cannot pull from repository`.

**Comment by s-junguy** [comment]
I deleted the directory /home/user/.nextflow/assets/nf-core/mag and then executed nextflow pull. It worked. Thank you!

**Comment by jfy133** [comment]
Glad you hear!
