### ISSUE TITLE
Please make --binning_map_mode group and --ancient-dna compatible features

### ISSUE THREAD

**Issue by winklerin** [nf-core/mag#572]
### Description of feature

Dear nf-core/mag team,
I'm working on aDNA sequences and would like to coassemble them while having the functions for ancient DNA assembly activated. I get the following error: 
Invalid combination of parameter '--binning_map_mode' and parameter '--ancient_dna'. Ancient DNA mode can only be executed with --binning_map_mode own. You supplied: --binning_map_mode group  
Might be a rare case, but for my samples it makes sense to coassemble. Could you please make  --binning_map_mode group and --ancient-dna compatible features?

**Comment by jfy133** [comment]
Hi @winklerin I assign this to Maxime as he has the most knowledge of the aDNA workflow :)

**Comment by jfy133** [comment]
Done in PRs aboev
