### ISSUE TITLE
Pipeline completed sucessfully, but with errored process(es)

### ISSUE THREAD

**Issue by Anenovaes** [nf-core/mag#610]
### Description of the bug

I successfully ran the pipeline; however, some processes did not execute, resulting in a failure in the MAGBIN2 process.
![copyscreenshot](https://github.com/nf-core/mag/assets/67133354/d20911aa-954b-4ced-81c8-4e0d4aca56f1)

The .command.log indicates:

```
WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
MaxBin 2.2.7
Input contig: input/MEGAHIT-magmax01.contigs.fa
Located abundance file [magmax01_mb2_depth.txt]
Thread: 6
out header: MEGAHIT-MaxBin2-magmax01
Searching against 107 marker genes to find starting seed contigs for [input/MEGAHIT-magmax01.contigs.fa]...
Running FragGeneScan....
Running HMMER hmmsearch....
Try harder to dig out marker genes from contigs.
Marker gene search reveals that the dataset cannot be binned (the medium of marker gene number <= 1). Program stop.
```

Despite running the pipeline with different sets of files, I consistently obtained the same results. Additionally, when attempting to parse more than one file as input, only one file was processed in the pipeline.

### Command used and terminal output

```console
nextflow run nf-core/mag -profile singularity --input /path/to/input_files/*.fastq.gz --outdir /path/to/output_dir --single_end --/path/to/host_reference --busco_db /data/busco/busco_downloads --busco_clean --run_virus_identification -resume
```

### System information

Nextflow version: 23.10.1
Executor:  local/server
Container engine: Singularity
OS: Ubuntu 22.04.2 LTS
Version of nf-core/mag: v2.5.4

**Comment by jfy133** [comment]
The errored process is fine, Unfortuantey MaxBIN2 fails entirely if it 'just' finds no bins, rather than just completing successfully and reporting 'no bins found'.

For the single file being run, I suspect this is because you've not wrapped the `--input` path and glob in a quotes:

```
--input '/path/to/input_files/*.fastq.gz'
```

Should then allow nextflow to evalute teh glob rather than bash :)
