### ISSUE TITLE
List of tool versions 

### ISSUE THREAD

**Issue by s-junguy** [nf-core/mag#612]
### Description of feature

Hi, is there any way to get all the specific versions of the tools that are used within the pipeline?

**Comment by jfy133** [comment]
Yes, this is listed at the end of the MultiQC report in the 'Software Versions' section

Example: https://nf-co.re/mag/2.5.4/results/mag/results-e486bb23b9012ecf649061f1eb448bb853e0aad8/multiqc/?file=multiqc_report.html

And in the YAML file in `pipleine_info/` in your results directory

Example: https://nf-co.re/mag/2.5.4/results/mag/results-e486bb23b9012ecf649061f1eb448bb853e0aad8/pipeline_info/?file=software_versions.yml
