### ISSUE TITLE
Skipping NFCORE_MAG:MAG:BOWTIE2_PHIX_REMOVAL_ALIGN

### ISSUE THREAD

**Issue by aboddicker** [nf-core/mag#619]
### Description of feature

I'd like to skip the "NFCORE_MAG:MAG:BOWTIE2_PHIX_REMOVAL_ALIGN" process. My reads are already removed of PhiX and I find this step to be very time consuming, even for lower numbers of reads (<100 million). Some jobs timeout after 6 hours (>100M reads). I've attempted to changer parameters in the config to "--very-fast" or increasing threads "-p" but the arguments are not recognized. I have not found a way to skip this process altogether. I am using Seqera Cloud to launch jobs. Thanks!

**Comment by jfy133** [comment]
Related: https://github.com/nf-core/mag/issues/455

**Comment by d4straub** [comment]
Why not use [--keep_phix](https://nf-co.re/mag/3.0.0/parameters#keep_phix) ? This should not run the process you are disliking, see https://github.com/nf-core/mag/blob/a50117e4ddc681b8ec5535fc265c66df45e38d30/workflows/mag.nf#L275-L287

**Comment by jfy133** [comment]
Yeah I forgot about that (I guess possibly the reason why @aboddicker also didn't recognise it, I find it rather unintuitive :sweat_smile: ) - please let us know if that works @aboddicker ! Then we close that and refer to the other issue for making the method of opting in/out more consistent

**Comment by aboddicker** [comment]
Thanks so much! Yes, this is a great solution. Selecting --keep_phix bypasses the alignment and proceeds simultaneously with FastQC and into assembly upon launch.
