### ISSUE TITLE
email function is not working

### ISSUE THREAD

**Issue by HaidYi** [nf-core/mag#642]
### Description of the bug

The bug is that the email function is not working. No email is delivered. But the log shows the email is sent successfully. 
Manually checked the code and find that 

```
def max_multiqc_email_size = (params.containsKey('max_multiqc_email_size') ? params.max_multiqc_email_size : 0) as nextflow.util.MemoryUnit
def smail_fields           = [ email: email_address, subject: subject, email_txt: email_txt, email_html: email_html, projectDir: "${workflow.projectDir}", mqcFile: mqc_report, mqcMaxSize: max_multiqc_email_size.toBytes() ]
def sf                     = new File("${workflow.projectDir}/assets/sendmail_template.txt")
def sendmail_template      = engine.createTemplate(sf).make(smail_fields)
def sendmail_html          = sendmail_template.toString()
```

The `sendmail_html` has length as 0. And the intermediate file `.sendmail_tmp.html` is also empty.

### Command used and terminal output

```console
nextflow run . -profile test,singularity --outdir results --email XXX@gmail.com
```

### System information

Nextflow version: both 23.04.4 and 24.04
Hardware: HPC
Executor: local
Container engine: both conda and singularity
OS: red hat linux-8
nf-core/mag: 3.0.2

**Comment by jfy133** [comment]
This is an upstream bug in the nf-core template, PR has already been made by @HaidYi to address it there :)

**Comment by edmundmiller** [comment]
Duplicate https://github.com/nf-core/tools/issues/3080
