### ISSUE TITLE
GUNC-GTDB overwriting output files for bins

### ISSUE THREAD

**Issue by zackhenny** [nf-core/mag#645]
### Description of the bug

GUNC is over writing each output file `GUNC.gtdb_95.maxCSS_level.tsv` is named the same, so every time GUNC runs on a new bin in the same sample/binner/assembler (e.g. MEGAHIT-MetaBAT2-prokarya-unrefined-SAMPLE1)  it overwrites the previous file as each gunc run has the same named output  `GUNC.gtdb_95.maxCSS_level.tsv`.  Everytime a new bin is processed from the same sample in GUNC it overwrites what has been done before it (ends with only one bin / sample and not bin collection).

### System information

nf-core MAG 3.0.2

nextflow/23.10.1

**Comment by jfy133** [comment]
Done and included in the upcoming patch release :)
