### ISSUE TITLE
`GTDBTK_CLASSIFYWF` does not use  `params.gtdbtk_pplacer_cpus`

### ISSUE THREAD

**Issue by harper357** [nf-core/mag#670]
### Description of the bug

`params.gtdbtk_pplacer_cpus` can be set, but it currently is not used in the process `GTDBTK_CLASSIFYWF`. 

Re: [Slack question](https://nfcore.slack.com/archives/CE9MS66BS/p1726251574827169)

I am happy to make a PR if someone knows/has thoughts on where I should add it. Meaning, should I make a PR on nf-core/modules, just modify `conf/module.config` and add it to the `task.ext.args`, or something else?

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/mag/pull/671/

**Comment by jfy133** [comment]
And thanks!
