### ISSUE TITLE
SPADES with exit code 12 when running out of memory

### ISSUE THREAD

**Issue by bawee** [nf-core/mag#675]
### Description of the bug

Hello,

SPADES seems to be exiting with exit code 12 when it runs out of memory. I wonder if this should be added to the exit codes that the pipeline recognises to retry SPADES with more RAM? Please see attached report.txt. 

Thanks!

### Relevant files

[pipeline_report.txt](https://github.com/user-attachments/files/17100515/pipeline_report.txt)

**Comment by jfy133** [comment]
Yup good idea!

**Comment by jfy133** [comment]
PR here: https://github.com/nf-core/mag/pull/676
