### ISSUE TITLE
Metabat2 said I have 0 bins. May I please have help to fix it?

### ISSUE THREAD

**Issue by lyisrae1** [nf-core/mag#696]
Hello,

I am trying to bin my MAGs for my metagenomic samples. I am trying to use Metabat2, but it says that I have 0 bins when there are over 1million contigs in a sample, and many are over 1500 bp. Here is my job submission and my log report. Can you please tell me what I am doing wrong? 

Job script: 
# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThC.q
#$ -l mres=3G,h_data=3G,h_vmem=3G
#$ -cwd
#$ -j y
#$ -N metabat2_practice
#$ -o metabat2_practice.log
#$ -m bea
#$ -M lyisrae1@jhu.edu
#
# ----------------Modules------------------------- #
module load tools/conda/3.11
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
source activate binning
jgi_summarize_bam_contig_depths --outputDepth 88_more-kmers_depth.txt 88_more-kmers_sorted.bam
mkdir Metabin
metabat2 -i 88_more-kmers_contigs.fasta -a 88_more-kmers_depth.txt -o ../Metabat/Metabin/bin -m 1500
conda deactivate binning
#
echo = `date` job $JOB_NAME done

Here is the logfile. 
[metabat2_practice.log](https://github.com/user-attachments/files/17402613/metabat2_practice.log)

Thank you so much for your help!

**Comment by jfy133** [comment]
Hello @lyisrae1 

This repository is for nf-core/mag support not general metagenomics support.

I will close this but you can maybe ask for help on the the nf-core slack and meta-omics channel and someone there might have experience with that specific tool
