### ISSUE TITLE
Process label is missing for kraken2

### ISSUE THREAD

**Issue by husensofteng** [nf-core/mag#723]
Hi,

It seems the local [`karken2` module](https://github.com/nf-core/mag/blob/b582aae7d64816e08d6efae7c82ed55ea20ee7b2/modules/local/kraken2.nf#L3) in `mag` has no assigned label (e.g. `process_high, process_medium, process_low`) and that makes it a bit difficult to assign resources in a high level manner within a config file. 
In fact the `[nf-core/kraken2](https://github.com/nf-core/modules/blob/f25bd4b911254bbbd4b5a1d434bed2a90a056927/modules/nf-core/kraken2/kraken2/main.nf#L3)` module has `process_high` label.

**Comment by jfy133** [comment]
Yes, we will get to updating that to the official module eventually 😅 (I've been doing this slowly over the last few months) 

But in the meantime, you can also specify this on a process name basis too:

```
withName: KRAKEN2 

```
