### ISSUE TITLE
Simplify `bin_summary.tsv`

### ISSUE THREAD

**Issue by dialvarezs** [nf-core/mag#725]
### Description of feature

The current `bin_summary.tsv` file is quite large, making it overwhelming to open for a quick overview. I know that it’s helpful for downstream analysis to consolidate everything into a single file, but it might be too much for a "summary," especially if we add more tools (e.g., multiple QC tools simultaneously).

I suggest we simplify the file by focusing on the key fields per tool. For example:

Quast: #contigs, total length, GC content, LXX, and NXX.
QC tools: completion, contamination (and possibly a few additional fields for BUSCO).
GTDB: taxonomy and ANI value.
Depths: Rather than including depths in the summary, we could move them to a separate file (e.g., `bin_depths.tsv`).

This way, that file would be a good source of key info, and if you want to dig deeper, you could look a the specific files of each tool.

Maybe this could be  configurable in some  way, like a param `--(full/compact)_bin_summary`. And also the selected fields can be in the config itself.

**Comment by jfy133** [comment]
Ooh, this might be a bit more controversial. 

Could you maybe post this on the slack channel?

 it will be easier to get every day user input on there.

**Comment by jfy133** [comment]
Discussion on slack pointed towards keeping the table as a raw one, but maybe making a nicer summary detailed report to condense the information (a la ampliseq) https://nf-core-awsmegatests.s3-eu-west-1.amazonaws.com/ampliseq/results-8f139cecd95a23920617f2c2b154733494ed4562/summary_report/summary_report.html

@dialvarezs can you make a new issue, and summarise from the slack thread?
