### ISSUE TITLE
checkm is not on conda

### ISSUE THREAD

**Issue by HadrienG** [nf-core/mag#8]
it would be nicer to have everything in conda. In the meantime a manual install in the Dockerfile will have to do.

**Comment by HadrienG** [comment]
Additionally checkm is python2 only so right now the following happens during the db install:

```
Successfully installed checkm-genome-1.0.12 dendropy-4.4.0 scipy-1.1.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  275M  100  275M    0     0  3542k      0  0:01:19  0:01:19 --:--:-- 5518k
  File "/opt/conda/envs/nf-core-mag-0.1.0dev/bin/checkm", line 58
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('')?
```

unfortunately atropos is python3 only so I can't downgrade python to python2 in the environment.

**Comment by apeltzer** [comment]
Repackage the recipe and run 2to3 on it beforehand in the build script? 

https://docs.python.org/2/library/2to3.html

**Comment by HadrienG** [comment]
Thanks! 2to3 didn't work out of the box unfortunately.

For now I'll go with two containers but will try to port checkm to python when I have some free time 😁

**Comment by HadrienG** [comment]
removing `atropos` removed the `python3` dependency so I'm back on 1 container for the whole workflow

still have a `pip install` in the dockerfile, but getting there!
