### ISSUE TITLE
Zcat fails on Mac OS X when using Conda

### ISSUE THREAD

**Issue by skrakau** [nf-core/mag#80]
`zcat foo.txt.gz` doesn't work on Mac OS X.

This causes `zcat ${name}_phix_unmapped_1.fastq.gz` in process `remove_phix` to fail on my Mac when using Conda:

`zcat: can't stat: test_minigut_trimmed_R1.fastq.gz (test_minigut_trimmed_R1.fastq.gz.Z): No such file or directory`

Think about how to handle this differently.

**Comment by skrakau** [comment]
Use simply `gunzip -c` or use Conda `pigz`,`coreutils` etc. in general?

**Comment by d4straub** [comment]
zcat is also used in `process nanolyse` [here](https://github.com/nf-core/mag/blob/1c400ba55ff5d0bce26ea1f52ee1fbedf5ecc926/main.nf#L694) and `process remove_host`.

As I see it, zcat in combination with | allows processing of compressed files without the need to store an uncompressed file (contrary to `gunzip -c`).

I am not sure how often the pipeline will be run on a Mac OS with conda in an actual metagenome assembly, I assume that this does not happen.

**Comment by skrakau** [comment]
Fixed in #93
