### ISSUE TITLE
Run design and implications for bowtie2 and MetaBAT2 steps

### ISSUE THREAD

**Issue by ropolomx** [nf-core/mag#91]
This is a question more than an issue. In previous conversations in Slack @skrakau helped me to understand the rationale of the `bowtie2` step (Thank you @skrakau!) In particular, she referred me to https://github.com/nf-core/mag/issues/21 and explained why does `mag` run `bowtie2` for all vs. all samples (i.e. _"it is required by MetaBAT for binning the reads from each sample to be aligned in separate BAM files, which is important to include the information from library specific abundances"_).  
I am analyzing 43 samples and I wonder if the design of the analysis run has an implication in the `bowtie2` step too. In this case, we have 43*43 = 1849 * 2 (I am comparing metaSPAdes vs. Megahit as well) =  3698 jobs. But not all of the 43 samples are from the same environment and geographical location. They come from 4 very different environments and most come from different geographical locations. Thus, I am not sure if the alignment of all samples vs. all would be appropriate in this case. Maybe I should have separated my samples by environment type. What do you think? Thank you for your time and dedication to this project.

**Comment by ropolomx** [comment]
It seems that https://github.com/nf-core/mag/issues/21#issuecomment-586836897 addresses my question, but I just wanted to make sure I am understanding the implications correctly. Thank you so much!

**Comment by d4straub** [comment]
Yes, one run of nf-core/mag should be done for samples with related microbial community, i.e. at least some genomes are expected to overlap. The bowtie settings are supposed to help binning with abundance information of a particular genome over a range of samples. If there are no/very few overlapping genomes, than this approach will be not beneficial (maybe even give wrong information).

**Comment by ropolomx** [comment]
Thank you for the clarification, @d4straub. This is very helpful! I feel like this should be stated more clearly in the documentation. I can help writing something, and I can open a PR. Perhaps there might be an use for an option to skip the all vs. all alignment (and just do mapping reads back to the individual assemblies). Some of the potential uses I was hoping to use MAG for could be to assemble public datasets for comparative metagenomics, many of which come from different sources. Sometimes we just want to compare MAGs that come from disparate sources, even from different geographical locations.

**Comment by d4straub** [comment]
Hm thats true. We could add such an option to skip the all vs. all alignment, just would need to evaluate how much change is needed, might be easy. For a large number of unrelated samples it might really be a time issue.
@HadrienG and @skrakau might also have an opinion whether this would be a useful addition.

**Comment by skrakau** [comment]
Yes, sounds good, we could add an option for this, but maybe after the release (depending on how soon we can make it, currently waiting for the Busco fix). 

@ropolomx a PR with description would be highly welcome ;) We are also planning to add an overview figure sometime soon.

**Comment by d4straub** [comment]
This is actually implemented in version 1.2.0.

**Comment by ropolomx** [comment]
Thank you @d4straub and @skrakau!! Looking forward to test 1.2.0!
