### ISSUE TITLE
bowtie2 log file contains stdout (sam file) 

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#97]
In `process remove_phix` log files contain stdout (sam file) and stderr and therefore can blow up to huge sizes. stdout in the log file seems absolutely unnecessary, it should only contain stderr.

This could be solved as in `process remove_host`:
```
bowtie2 [...] \
1> /dev/null \
2> ${name}.bowtie2.log
```

**Comment by skrakau** [comment]
solved in #101
